/* Automatic generated by DeviceToClazz */

package miot.api.device.xiaomi;

import android.os.Parcel;

import jing.api.device.AbstractDevice;
import jing.api.device.dlna.service.ContentDirectory;
import jing.api.device.dlna.service.RemoteControl;
import jing.typedef.device.Device;
import jing.typedef.device.Service;

public class MediaServer extends AbstractDevice {

    private ContentDirectory _ContentDirectory;
    private RemoteControl _RemoteControl;

    public ContentDirectory getContentDirectory() {
        return _ContentDirectory;
    }
    public RemoteControl getRemoteControl() {
        return _RemoteControl;
    }

    private static final Object classLock = MediaServer.class;
    private static final String DEVICE_TYPE = "MediaServer";
    private static final String ID_ContentDirectory = "urn:upnp-org:serviceId:ContentDirectory";
    private static final String ID_RemoteControl = "urn:upnp-org:serviceId:RemoteControl";

    public static MediaServer create(Device device) {
        synchronized (classLock) {
            MediaServer thiz = new MediaServer(device);
                
            do {
                if (! DEVICE_TYPE.equals(device.getDeviceType().getName())) {
                    thiz = null;
                    break;
                }

                if (! thiz.initialize()) {
                    thiz = null;
                    break;
                }
            } while (false);

            return thiz;
        }
    }

    private MediaServer(Device device) {
        this.device = device;
    }

    private boolean initialize() {
        boolean ret = false;

        do {
            Service theContentDirectory = device.getService(ID_ContentDirectory);
            if (theContentDirectory == null) {
                break;
            }

            Service theRemoteControl = device.getService(ID_RemoteControl);
            if (theRemoteControl == null) {
                break;
            }

            _ContentDirectory = new ContentDirectory(theContentDirectory);
            _RemoteControl = new RemoteControl(theRemoteControl);

            ret = true;
        } while (false);

        return ret;
    }

    public static final Creator<MediaServer> CREATOR = new Creator<MediaServer>() {

        @Override
        public MediaServer createFromParcel(Parcel in) {
            return new MediaServer(in);
        }

        @Override
        public MediaServer[] newArray(int size) {
            return new MediaServer[size];
         }
    };

    private MediaServer(Parcel in) {
        readFromParcel(in);
    }

    public void readFromParcel(Parcel in) {
        device = in.readParcelable(Device.class.getClassLoader());
        initialize();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel out, int flags) {
        out.writeParcelable(device, flags);
    }
}
