/* Automatic generated by DeviceToClazz */

package miot.api.device.xiaomi;

import android.os.Parcel;

import jing.api.device.AbstractDevice;
import jing.api.device.dlna.service.AirTunes;
import jing.typedef.device.Device;
import jing.typedef.device.Service;

public class AirportExpress extends AbstractDevice {

    private AirTunes _AirTunes;

    public AirTunes getAirTunes() {
        return _AirTunes;
    }

    private static final Object classLock = AirportExpress.class;
    private static final String DEVICE_TYPE = "AirportExpress";
    private static final String ID_AirTunes = "urn:upnp-org:serviceId:AirTunes";

    public static AirportExpress create(Device device) {
        synchronized (classLock) {
            AirportExpress thiz = new AirportExpress(device);
                
            do {
                if (! DEVICE_TYPE.equals(device.getDeviceType().getName())) {
                    thiz = null;
                    break;
                }

                if (! thiz.initialize()) {
                    thiz = null;
                    break;
                }
            } while (false);

            return thiz;
        }
    }

    private AirportExpress(Device device) {
        this.device = device;
    }

    private boolean initialize() {
        boolean ret = false;

        do {
            Service theAirTunes = device.getService(ID_AirTunes);
            if (theAirTunes == null) {
                break;
            }

            _AirTunes = new AirTunes(theAirTunes);

            ret = true;
        } while (false);

        return ret;
    }

    public static final Creator<AirportExpress> CREATOR = new Creator<AirportExpress>() {

        @Override
        public AirportExpress createFromParcel(Parcel in) {
            return new AirportExpress(in);
        }

        @Override
        public AirportExpress[] newArray(int size) {
            return new AirportExpress[size];
         }
    };

    private AirportExpress(Parcel in) {
        readFromParcel(in);
    }

    public void readFromParcel(Parcel in) {
        device = in.readParcelable(Device.class.getClassLoader());
        initialize();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel out, int flags) {
        out.writeParcelable(device, flags);
    }
}
