/* Automatic generated by DeviceToC */

#include "BleOperation.h"
#include "tiny_memory.h"
#include "tiny_str_equal.h"
#include "tiny_log.h"
#include "UpnpCode.h"
#include "UpnpEvent.h"

#define TAG             "BleOperation"

static const char * _SERVICE_TYPE = "urn:schemas-upnp-org:service:BleOperation:0.1";

//-------------------------------------------------------
// Action Names (10)
//-------------------------------------------------------
static const char * ACTION_StartScan = "StartScan";
static const char * _StartScan_ARG_Fileter = "Fileter";
static const char * ACTION_WriteCharacteristic = "WriteCharacteristic";
static const char * _WriteCharacteristic_ARG_BleDevice = "BleDevice";
static const char * _WriteCharacteristic_ARG_BleService = "BleService";
static const char * _WriteCharacteristic_ARG_BleCharacteristic = "BleCharacteristic";
static const char * _WriteCharacteristic_ARG_Data = "Data";
static const char * ACTION_KeepAlive = "KeepAlive";
static const char * _KeepAlive_ARG_BleDevice = "BleDevice";
static const char * ACTION_DiscoverServices = "DiscoverServices";
static const char * _DiscoverServices_ARG_BleDevice = "BleDevice";
static const char * ACTION_EnableCharacteristicNotification = "EnableCharacteristicNotification";
static const char * _EnableCharacteristicNotification_ARG_BleDevice = "BleDevice";
static const char * _EnableCharacteristicNotification_ARG_BleService = "BleService";
static const char * _EnableCharacteristicNotification_ARG_BleCharacteristic = "BleCharacteristic";
static const char * ACTION_ReadCharacteristic = "ReadCharacteristic";
static const char * _ReadCharacteristic_ARG_BleDevice = "BleDevice";
static const char * _ReadCharacteristic_ARG_BleService = "BleService";
static const char * _ReadCharacteristic_ARG_BleCharacteristic = "BleCharacteristic";
static const char * ACTION_getConnectedDevices = "getConnectedDevices";
static const char * _getConnectedDevices_ARG_RetAvaliableDevices = "RetAvaliableDevices";
static const char * ACTION_getAvaliableDevices = "getAvaliableDevices";
static const char * _getAvaliableDevices_ARG_RetAvaliableDevices = "RetAvaliableDevices";
static const char * ACTION_StopScan = "StopScan";
static const char * ACTION_DisableCharacteristicNotification = "DisableCharacteristicNotification";
static const char * _DisableCharacteristicNotification_ARG_BleDevice = "BleDevice";
static const char * _DisableCharacteristicNotification_ARG_BleService = "BleService";
static const char * _DisableCharacteristicNotification_ARG_BleCharacteristic = "BleCharacteristic";

//-------------------------------------------------------
// Property Name (11)
//-------------------------------------------------------
static const char * PROPERTY_CharacteristicReaded = "CharacteristicReaded";
static const char * PROPERTY_A_ARG_TYPE_BleCharacteristic = "A_ARG_TYPE_BleCharacteristic";
static const char * PROPERTY_A_ARG_TYPE_BleService = "A_ARG_TYPE_BleService";
static const char * PROPERTY_A_ARG_TYPE_BleDevices = "A_ARG_TYPE_BleDevices";
static const char * PROPERTY_ScanResult = "ScanResult";
static const char * PROPERTY_CharacteristicNotified = "CharacteristicNotified";
static const char * PROPERTY_A_ARG_TYPE_BleDevice = "A_ARG_TYPE_BleDevice";
static const char * PROPERTY_A_ARG_TYPE_Filter = "A_ARG_TYPE_Filter";
static const char * PROPERTY_CharacteristicWrited = "CharacteristicWrited";
static const char * PROPERTY_A_ARG_TYPE_Data = "A_ARG_TYPE_Data";
static const char * PROPERTY_DiscoveredServices = "DiscoveredServices";

//-------------------------------------------------------
// Property value defined (0)
//-------------------------------------------------------

static void event_listener(UpnpEvent *event, void *ctx);

struct _BleOperation {
    UpnpService *service;
    UpnpRuntime *runtime;
    char subscriptionId[UPNP_UUID_LEN];
    BleOperation_SubscriptionExpired onSubscriptionExpired;
    BleOperation_CharacteristicReadedChanged  onCharacteristicReadedChanged;
    BleOperation_ScanResultChanged  onScanResultChanged;
    BleOperation_CharacteristicNotifiedChanged  onCharacteristicNotifiedChanged;
    BleOperation_CharacteristicWritedChanged  onCharacteristicWritedChanged;
    BleOperation_DiscoveredServicesChanged  onDiscoveredServicesChanged;
    void *ctx;
};

BleOperation * BleOperation_Create(UpnpService *service, UpnpRuntime *runtime) {
    BleOperation * thiz = NULL;

    RETURN_VAL_IF_FAIL(service, NULL);
    RETURN_VAL_IF_FAIL(runtime, NULL);

    do {
        thiz = (BleOperation *)tiny_malloc(sizeof(BleOperation));
        if (thiz == NULL) {
            LOG_E(TAG, "OUT OF MEMORY!");
            break;
        }

        memset(thiz, 0, sizeof(BleOperation));
        thiz->service = service;
        thiz->runtime = runtime;

        if (!STR_EQUAL(_SERVICE_TYPE, UpnpService_GetServiceType(service))) {
            LOG_E(TAG, "SERVICE_TYPE invalid: %s", UpnpService_GetServiceType(service));
            BleOperation_Delete(thiz);
            thiz = NULL;
            break;
        }
    } while (0);

    return thiz;
}

void BleOperation_Delete(BleOperation *thiz) {
    RETURN_IF_FAIL(thiz);
    tiny_free(thiz);
}

TinyRet BleOperation_StartScan(BleOperation *thiz, char * Fileter,UpnpError *error) {
    TinyRet ret = TINY_RET_OK;

    RETURN_VAL_IF_FAIL(thiz, TINY_RET_E_ARG_NULL);
    RETURN_VAL_IF_FAIL(error, TINY_RET_E_ARG_NULL);

    do {
        UpnpAction *action = UpnpService_GetAction(thiz->service, ACTION_StartScan);
        if (action == NULL) {
            ret = TINY_RET_E_UPNP_ACTION_NOT_FOUND;
            break;
        }

        UpnpStateVariable * _Fileter = UpnpService_GetStateVariable(thiz->service, UpnpAction_GetArgumentRelatedStateVariable(action, _StartScan_ARG_Fileter));
        if (_Fileter == NULL) {
            LOG_E(TAG, "Result invalid: %s NOT FOUND!", _StartScan_ARG_Fileter);
            break;
        }

        _Fileter->value.internalValue.stringValue = Fileter;

        ret = UpnpRuntime_Invoke(thiz->runtime, action, error);
        if (ret != TINY_RET_OK) {
            break;
        }

        if (error->code != UPNP_SUCCESS) {
            break;
        }
    } while (0);

    return ret;
}

TinyRet BleOperation_WriteCharacteristic(BleOperation *thiz, char * BleDevice, char * BleService, char * BleCharacteristic, char * Data,UpnpError *error) {
    TinyRet ret = TINY_RET_OK;

    RETURN_VAL_IF_FAIL(thiz, TINY_RET_E_ARG_NULL);
    RETURN_VAL_IF_FAIL(error, TINY_RET_E_ARG_NULL);

    do {
        UpnpAction *action = UpnpService_GetAction(thiz->service, ACTION_WriteCharacteristic);
        if (action == NULL) {
            ret = TINY_RET_E_UPNP_ACTION_NOT_FOUND;
            break;
        }

        UpnpStateVariable * _BleDevice = UpnpService_GetStateVariable(thiz->service, UpnpAction_GetArgumentRelatedStateVariable(action, _WriteCharacteristic_ARG_BleDevice));
        if (_BleDevice == NULL) {
            LOG_E(TAG, "Result invalid: %s NOT FOUND!", _WriteCharacteristic_ARG_BleDevice);
            break;
        }

        _BleDevice->value.internalValue.stringValue = BleDevice;
        UpnpStateVariable * _BleService = UpnpService_GetStateVariable(thiz->service, UpnpAction_GetArgumentRelatedStateVariable(action, _WriteCharacteristic_ARG_BleService));
        if (_BleService == NULL) {
            LOG_E(TAG, "Result invalid: %s NOT FOUND!", _WriteCharacteristic_ARG_BleService);
            break;
        }

        _BleService->value.internalValue.stringValue = BleService;
        UpnpStateVariable * _BleCharacteristic = UpnpService_GetStateVariable(thiz->service, UpnpAction_GetArgumentRelatedStateVariable(action, _WriteCharacteristic_ARG_BleCharacteristic));
        if (_BleCharacteristic == NULL) {
            LOG_E(TAG, "Result invalid: %s NOT FOUND!", _WriteCharacteristic_ARG_BleCharacteristic);
            break;
        }

        _BleCharacteristic->value.internalValue.stringValue = BleCharacteristic;
        UpnpStateVariable * _Data = UpnpService_GetStateVariable(thiz->service, UpnpAction_GetArgumentRelatedStateVariable(action, _WriteCharacteristic_ARG_Data));
        if (_Data == NULL) {
            LOG_E(TAG, "Result invalid: %s NOT FOUND!", _WriteCharacteristic_ARG_Data);
            break;
        }

        _Data->value.internalValue.stringValue = Data;

        ret = UpnpRuntime_Invoke(thiz->runtime, action, error);
        if (ret != TINY_RET_OK) {
            break;
        }

        if (error->code != UPNP_SUCCESS) {
            break;
        }
    } while (0);

    return ret;
}

TinyRet BleOperation_KeepAlive(BleOperation *thiz, char * BleDevice,UpnpError *error) {
    TinyRet ret = TINY_RET_OK;

    RETURN_VAL_IF_FAIL(thiz, TINY_RET_E_ARG_NULL);
    RETURN_VAL_IF_FAIL(error, TINY_RET_E_ARG_NULL);

    do {
        UpnpAction *action = UpnpService_GetAction(thiz->service, ACTION_KeepAlive);
        if (action == NULL) {
            ret = TINY_RET_E_UPNP_ACTION_NOT_FOUND;
            break;
        }

        UpnpStateVariable * _BleDevice = UpnpService_GetStateVariable(thiz->service, UpnpAction_GetArgumentRelatedStateVariable(action, _KeepAlive_ARG_BleDevice));
        if (_BleDevice == NULL) {
            LOG_E(TAG, "Result invalid: %s NOT FOUND!", _KeepAlive_ARG_BleDevice);
            break;
        }

        _BleDevice->value.internalValue.stringValue = BleDevice;

        ret = UpnpRuntime_Invoke(thiz->runtime, action, error);
        if (ret != TINY_RET_OK) {
            break;
        }

        if (error->code != UPNP_SUCCESS) {
            break;
        }
    } while (0);

    return ret;
}

TinyRet BleOperation_DiscoverServices(BleOperation *thiz, char * BleDevice,UpnpError *error) {
    TinyRet ret = TINY_RET_OK;

    RETURN_VAL_IF_FAIL(thiz, TINY_RET_E_ARG_NULL);
    RETURN_VAL_IF_FAIL(error, TINY_RET_E_ARG_NULL);

    do {
        UpnpAction *action = UpnpService_GetAction(thiz->service, ACTION_DiscoverServices);
        if (action == NULL) {
            ret = TINY_RET_E_UPNP_ACTION_NOT_FOUND;
            break;
        }

        UpnpStateVariable * _BleDevice = UpnpService_GetStateVariable(thiz->service, UpnpAction_GetArgumentRelatedStateVariable(action, _DiscoverServices_ARG_BleDevice));
        if (_BleDevice == NULL) {
            LOG_E(TAG, "Result invalid: %s NOT FOUND!", _DiscoverServices_ARG_BleDevice);
            break;
        }

        _BleDevice->value.internalValue.stringValue = BleDevice;

        ret = UpnpRuntime_Invoke(thiz->runtime, action, error);
        if (ret != TINY_RET_OK) {
            break;
        }

        if (error->code != UPNP_SUCCESS) {
            break;
        }
    } while (0);

    return ret;
}

TinyRet BleOperation_EnableCharacteristicNotification(BleOperation *thiz, char * BleDevice, char * BleService, char * BleCharacteristic,UpnpError *error) {
    TinyRet ret = TINY_RET_OK;

    RETURN_VAL_IF_FAIL(thiz, TINY_RET_E_ARG_NULL);
    RETURN_VAL_IF_FAIL(error, TINY_RET_E_ARG_NULL);

    do {
        UpnpAction *action = UpnpService_GetAction(thiz->service, ACTION_EnableCharacteristicNotification);
        if (action == NULL) {
            ret = TINY_RET_E_UPNP_ACTION_NOT_FOUND;
            break;
        }

        UpnpStateVariable * _BleDevice = UpnpService_GetStateVariable(thiz->service, UpnpAction_GetArgumentRelatedStateVariable(action, _EnableCharacteristicNotification_ARG_BleDevice));
        if (_BleDevice == NULL) {
            LOG_E(TAG, "Result invalid: %s NOT FOUND!", _EnableCharacteristicNotification_ARG_BleDevice);
            break;
        }

        _BleDevice->value.internalValue.stringValue = BleDevice;
        UpnpStateVariable * _BleService = UpnpService_GetStateVariable(thiz->service, UpnpAction_GetArgumentRelatedStateVariable(action, _EnableCharacteristicNotification_ARG_BleService));
        if (_BleService == NULL) {
            LOG_E(TAG, "Result invalid: %s NOT FOUND!", _EnableCharacteristicNotification_ARG_BleService);
            break;
        }

        _BleService->value.internalValue.stringValue = BleService;
        UpnpStateVariable * _BleCharacteristic = UpnpService_GetStateVariable(thiz->service, UpnpAction_GetArgumentRelatedStateVariable(action, _EnableCharacteristicNotification_ARG_BleCharacteristic));
        if (_BleCharacteristic == NULL) {
            LOG_E(TAG, "Result invalid: %s NOT FOUND!", _EnableCharacteristicNotification_ARG_BleCharacteristic);
            break;
        }

        _BleCharacteristic->value.internalValue.stringValue = BleCharacteristic;

        ret = UpnpRuntime_Invoke(thiz->runtime, action, error);
        if (ret != TINY_RET_OK) {
            break;
        }

        if (error->code != UPNP_SUCCESS) {
            break;
        }
    } while (0);

    return ret;
}

TinyRet BleOperation_ReadCharacteristic(BleOperation *thiz, char * BleDevice, char * BleService, char * BleCharacteristic,UpnpError *error) {
    TinyRet ret = TINY_RET_OK;

    RETURN_VAL_IF_FAIL(thiz, TINY_RET_E_ARG_NULL);
    RETURN_VAL_IF_FAIL(error, TINY_RET_E_ARG_NULL);

    do {
        UpnpAction *action = UpnpService_GetAction(thiz->service, ACTION_ReadCharacteristic);
        if (action == NULL) {
            ret = TINY_RET_E_UPNP_ACTION_NOT_FOUND;
            break;
        }

        UpnpStateVariable * _BleDevice = UpnpService_GetStateVariable(thiz->service, UpnpAction_GetArgumentRelatedStateVariable(action, _ReadCharacteristic_ARG_BleDevice));
        if (_BleDevice == NULL) {
            LOG_E(TAG, "Result invalid: %s NOT FOUND!", _ReadCharacteristic_ARG_BleDevice);
            break;
        }

        _BleDevice->value.internalValue.stringValue = BleDevice;
        UpnpStateVariable * _BleService = UpnpService_GetStateVariable(thiz->service, UpnpAction_GetArgumentRelatedStateVariable(action, _ReadCharacteristic_ARG_BleService));
        if (_BleService == NULL) {
            LOG_E(TAG, "Result invalid: %s NOT FOUND!", _ReadCharacteristic_ARG_BleService);
            break;
        }

        _BleService->value.internalValue.stringValue = BleService;
        UpnpStateVariable * _BleCharacteristic = UpnpService_GetStateVariable(thiz->service, UpnpAction_GetArgumentRelatedStateVariable(action, _ReadCharacteristic_ARG_BleCharacteristic));
        if (_BleCharacteristic == NULL) {
            LOG_E(TAG, "Result invalid: %s NOT FOUND!", _ReadCharacteristic_ARG_BleCharacteristic);
            break;
        }

        _BleCharacteristic->value.internalValue.stringValue = BleCharacteristic;

        ret = UpnpRuntime_Invoke(thiz->runtime, action, error);
        if (ret != TINY_RET_OK) {
            break;
        }

        if (error->code != UPNP_SUCCESS) {
            break;
        }
    } while (0);

    return ret;
}

TinyRet BleOperation_getConnectedDevices(BleOperation *thiz, BleOperation_getConnectedDevicesResult *result,UpnpError *error) {
    TinyRet ret = TINY_RET_OK;

    RETURN_VAL_IF_FAIL(thiz, TINY_RET_E_ARG_NULL);
    RETURN_VAL_IF_FAIL(error, TINY_RET_E_ARG_NULL);
    RETURN_VAL_IF_FAIL(result, TINY_RET_E_ARG_NULL);

    do {
        UpnpAction *action = UpnpService_GetAction(thiz->service, ACTION_getConnectedDevices);
        if (action == NULL) {
            ret = TINY_RET_E_UPNP_ACTION_NOT_FOUND;
            break;
        }


        ret = UpnpRuntime_Invoke(thiz->runtime, action, error);
        if (ret != TINY_RET_OK) {
            break;
        }

        if (error->code != UPNP_SUCCESS) {
            break;
        }
        UpnpStateVariable * _RetAvaliableDevices = UpnpService_GetStateVariable(thiz->service, UpnpAction_GetArgumentRelatedStateVariable(action, _getConnectedDevices_ARG_RetAvaliableDevices));
        if (_RetAvaliableDevices == NULL) {
            LOG_E(TAG, "Result invalid: %s NOT FOUND!", _getConnectedDevices_ARG_RetAvaliableDevices);
            break;
        }

        result->theRetAvaliableDevices = _RetAvaliableDevices->value.internalValue.stringValue;
    } while (0);

    return ret;
}

TinyRet BleOperation_getAvaliableDevices(BleOperation *thiz, BleOperation_getAvaliableDevicesResult *result,UpnpError *error) {
    TinyRet ret = TINY_RET_OK;

    RETURN_VAL_IF_FAIL(thiz, TINY_RET_E_ARG_NULL);
    RETURN_VAL_IF_FAIL(error, TINY_RET_E_ARG_NULL);
    RETURN_VAL_IF_FAIL(result, TINY_RET_E_ARG_NULL);

    do {
        UpnpAction *action = UpnpService_GetAction(thiz->service, ACTION_getAvaliableDevices);
        if (action == NULL) {
            ret = TINY_RET_E_UPNP_ACTION_NOT_FOUND;
            break;
        }


        ret = UpnpRuntime_Invoke(thiz->runtime, action, error);
        if (ret != TINY_RET_OK) {
            break;
        }

        if (error->code != UPNP_SUCCESS) {
            break;
        }
        UpnpStateVariable * _RetAvaliableDevices = UpnpService_GetStateVariable(thiz->service, UpnpAction_GetArgumentRelatedStateVariable(action, _getAvaliableDevices_ARG_RetAvaliableDevices));
        if (_RetAvaliableDevices == NULL) {
            LOG_E(TAG, "Result invalid: %s NOT FOUND!", _getAvaliableDevices_ARG_RetAvaliableDevices);
            break;
        }

        result->theRetAvaliableDevices = _RetAvaliableDevices->value.internalValue.stringValue;
    } while (0);

    return ret;
}

TinyRet BleOperation_StopScan(BleOperation *thiz,UpnpError *error) {
    TinyRet ret = TINY_RET_OK;

    RETURN_VAL_IF_FAIL(thiz, TINY_RET_E_ARG_NULL);
    RETURN_VAL_IF_FAIL(error, TINY_RET_E_ARG_NULL);

    do {
        UpnpAction *action = UpnpService_GetAction(thiz->service, ACTION_StopScan);
        if (action == NULL) {
            ret = TINY_RET_E_UPNP_ACTION_NOT_FOUND;
            break;
        }


        ret = UpnpRuntime_Invoke(thiz->runtime, action, error);
        if (ret != TINY_RET_OK) {
            break;
        }

        if (error->code != UPNP_SUCCESS) {
            break;
        }
    } while (0);

    return ret;
}

TinyRet BleOperation_DisableCharacteristicNotification(BleOperation *thiz, char * BleDevice, char * BleService, char * BleCharacteristic,UpnpError *error) {
    TinyRet ret = TINY_RET_OK;

    RETURN_VAL_IF_FAIL(thiz, TINY_RET_E_ARG_NULL);
    RETURN_VAL_IF_FAIL(error, TINY_RET_E_ARG_NULL);

    do {
        UpnpAction *action = UpnpService_GetAction(thiz->service, ACTION_DisableCharacteristicNotification);
        if (action == NULL) {
            ret = TINY_RET_E_UPNP_ACTION_NOT_FOUND;
            break;
        }

        UpnpStateVariable * _BleDevice = UpnpService_GetStateVariable(thiz->service, UpnpAction_GetArgumentRelatedStateVariable(action, _DisableCharacteristicNotification_ARG_BleDevice));
        if (_BleDevice == NULL) {
            LOG_E(TAG, "Result invalid: %s NOT FOUND!", _DisableCharacteristicNotification_ARG_BleDevice);
            break;
        }

        _BleDevice->value.internalValue.stringValue = BleDevice;
        UpnpStateVariable * _BleService = UpnpService_GetStateVariable(thiz->service, UpnpAction_GetArgumentRelatedStateVariable(action, _DisableCharacteristicNotification_ARG_BleService));
        if (_BleService == NULL) {
            LOG_E(TAG, "Result invalid: %s NOT FOUND!", _DisableCharacteristicNotification_ARG_BleService);
            break;
        }

        _BleService->value.internalValue.stringValue = BleService;
        UpnpStateVariable * _BleCharacteristic = UpnpService_GetStateVariable(thiz->service, UpnpAction_GetArgumentRelatedStateVariable(action, _DisableCharacteristicNotification_ARG_BleCharacteristic));
        if (_BleCharacteristic == NULL) {
            LOG_E(TAG, "Result invalid: %s NOT FOUND!", _DisableCharacteristicNotification_ARG_BleCharacteristic);
            break;
        }

        _BleCharacteristic->value.internalValue.stringValue = BleCharacteristic;

        ret = UpnpRuntime_Invoke(thiz->runtime, action, error);
        if (ret != TINY_RET_OK) {
            break;
        }

        if (error->code != UPNP_SUCCESS) {
            break;
        }
    } while (0);

    return ret;
}

TinyRet BleOperation_Subscribe(BleOperation *thiz,
    BleOperation_SubscriptionExpired onSubscriptionExpired,
    BleOperation_CharacteristicReadedChanged onCharacteristicReadedChanged,
    BleOperation_ScanResultChanged onScanResultChanged,
    BleOperation_CharacteristicNotifiedChanged onCharacteristicNotifiedChanged,
    BleOperation_CharacteristicWritedChanged onCharacteristicWritedChanged,
    BleOperation_DiscoveredServicesChanged onDiscoveredServicesChanged,
    UpnpError *error,
    void *ctx) {
    TinyRet ret = TINY_RET_OK;

    RETURN_VAL_IF_FAIL(thiz, TINY_RET_E_ARG_NULL);
    RETURN_VAL_IF_FAIL(error, TINY_RET_E_ARG_NULL);

    do {
        thiz->ctx = ctx;
        thiz->onSubscriptionExpired = onSubscriptionExpired;
        thiz->onCharacteristicReadedChanged = onCharacteristicReadedChanged;
        thiz->onScanResultChanged = onScanResultChanged;
        thiz->onCharacteristicNotifiedChanged = onCharacteristicNotifiedChanged;
        thiz->onCharacteristicWritedChanged = onCharacteristicWritedChanged;
        thiz->onDiscoveredServicesChanged = onDiscoveredServicesChanged;
        thiz->ctx = ctx;

        ret = UpnpRuntime_Subscribe(thiz->runtime, thiz->service, 0, event_listener, thiz, error);
        if (RET_FAILED(ret)) {
            break;
        }
    } while (0);

    return ret;
}

TinyRet BleOperation_Unsubscribe(BleOperation *thiz, UpnpError *error) {
    TinyRet ret = TINY_RET_OK;

    RETURN_VAL_IF_FAIL(thiz, TINY_RET_E_ARG_NULL);
    RETURN_VAL_IF_FAIL(error, TINY_RET_E_ARG_NULL);

    ret = UpnpRuntime_Unsubscribe(thiz->runtime, thiz->service, error);
    if (RET_SUCCEEDED(ret)) {
        thiz->onSubscriptionExpired = NULL;
        thiz->onCharacteristicReadedChanged = NULL;
        thiz->onScanResultChanged = NULL;
        thiz->onCharacteristicNotifiedChanged = NULL;
        thiz->onCharacteristicWritedChanged = NULL;
        thiz->onDiscoveredServicesChanged = NULL;
        thiz->ctx = NULL;
    }

    return ret;
}

static void event_listener(UpnpEvent *event, void *ctx) {
    BleOperation *thiz = (BleOperation *)ctx;

    LOG_D(TAG, "event_listener");

    do {
        const char * _characteristicreaded = UpnpEvent_GetArgumentValue(event, PROPERTY_CharacteristicReaded);
        if (_characteristicreaded != NULL) {
            if (thiz->onCharacteristicReadedChanged != NULL) {
                thiz->onCharacteristicReadedChanged(_characteristicreaded, thiz->ctx);
            }
        }
        const char * _scanresult = UpnpEvent_GetArgumentValue(event, PROPERTY_ScanResult);
        if (_scanresult != NULL) {
            if (thiz->onScanResultChanged != NULL) {
                thiz->onScanResultChanged(_scanresult, thiz->ctx);
            }
        }
        const char * _characteristicnotified = UpnpEvent_GetArgumentValue(event, PROPERTY_CharacteristicNotified);
        if (_characteristicnotified != NULL) {
            if (thiz->onCharacteristicNotifiedChanged != NULL) {
                thiz->onCharacteristicNotifiedChanged(_characteristicnotified, thiz->ctx);
            }
        }
        const char * _characteristicwrited = UpnpEvent_GetArgumentValue(event, PROPERTY_CharacteristicWrited);
        if (_characteristicwrited != NULL) {
            if (thiz->onCharacteristicWritedChanged != NULL) {
                thiz->onCharacteristicWritedChanged(_characteristicwrited, thiz->ctx);
            }
        }
        const char * _discoveredservices = UpnpEvent_GetArgumentValue(event, PROPERTY_DiscoveredServices);
        if (_discoveredservices != NULL) {
            if (thiz->onDiscoveredServicesChanged != NULL) {
                thiz->onDiscoveredServicesChanged(_discoveredservices, thiz->ctx);
            }
        }
    } while (0);
}

