/* Automatic generated by DeviceToClazz */

package upnps.api.host.device.mediarenderer;

import android.util.Log;

import upnp.typedef.datatype.DataType;
import upnp.typedef.device.Action;
import upnp.typedef.device.Device;
import upnp.typedef.device.urn.ServiceType;
import upnp.typedef.error.UpnpError;
import upnp.typedef.device.Argument;
import upnp.typedef.device.Service;
import upnp.typedef.device.invocation.ActionInfo;
import upnp.typedef.device.invocation.EventInfo;
import upnp.typedef.device.invocation.EventInfoCreator;
import upnp.typedef.exception.UpnpException;

import upnp.typedef.property.AllowedValueList;
import upnp.typedef.property.AllowedValueRange;
import upnp.typedef.property.PropertyDefinition;
import upnps.manager.UpnpManager;
import upnps.manager.host.ServiceHandler;

public class AVTransport extends ServiceHandler {
    private static final String TAG = "AVTransport";
    private static final ServiceType SERVICE_TYPE =  new ServiceType("AVTransport", "1");

    //-------------------------------------------------------
    // Action Names (13)
    //-------------------------------------------------------
    public static final String ACTION_Next = "Next";
    public static final String _Next_ARG_InstanceID = "InstanceID";
    public static final String ACTION_Seek = "Seek";
    public static final String _Seek_ARG_InstanceID = "InstanceID";
    public static final String _Seek_ARG_Unit = "Unit";
    public static final String _Seek_ARG_Target = "Target";
    public static final String ACTION_Play = "Play";
    public static final String _Play_ARG_InstanceID = "InstanceID";
    public static final String _Play_ARG_Speed = "Speed";
    public static final String ACTION_GetTransportInfo = "GetTransportInfo";
    public static final String _GetTransportInfo_ARG_InstanceID = "InstanceID";
    public static final String _GetTransportInfo_ARG_CurrentTransportState = "CurrentTransportState";
    public static final String _GetTransportInfo_ARG_CurrentTransportStatus = "CurrentTransportStatus";
    public static final String _GetTransportInfo_ARG_CurrentSpeed = "CurrentSpeed";
    public static final String ACTION_Previous = "Previous";
    public static final String _Previous_ARG_InstanceID = "InstanceID";
    public static final String ACTION_GetMediaInfo = "GetMediaInfo";
    public static final String _GetMediaInfo_ARG_InstanceID = "InstanceID";
    public static final String _GetMediaInfo_ARG_NrTracks = "NrTracks";
    public static final String _GetMediaInfo_ARG_MediaDuration = "MediaDuration";
    public static final String _GetMediaInfo_ARG_CurrentURI = "CurrentURI";
    public static final String _GetMediaInfo_ARG_CurrentURIMetaData = "CurrentURIMetaData";
    public static final String _GetMediaInfo_ARG_NextURI = "NextURI";
    public static final String _GetMediaInfo_ARG_NextURIMetaData = "NextURIMetaData";
    public static final String _GetMediaInfo_ARG_PlayMedium = "PlayMedium";
    public static final String _GetMediaInfo_ARG_RecordMedium = "RecordMedium";
    public static final String _GetMediaInfo_ARG_WriteStatus = "WriteStatus";
    public static final String ACTION_GetDeviceCapabilities = "GetDeviceCapabilities";
    public static final String _GetDeviceCapabilities_ARG_InstanceID = "InstanceID";
    public static final String _GetDeviceCapabilities_ARG_PlayMedia = "PlayMedia";
    public static final String _GetDeviceCapabilities_ARG_RecMedia = "RecMedia";
    public static final String _GetDeviceCapabilities_ARG_RecQualityModes = "RecQualityModes";
    public static final String ACTION_Pause = "Pause";
    public static final String _Pause_ARG_InstanceID = "InstanceID";
    public static final String ACTION_GetCurrentTransportActions = "GetCurrentTransportActions";
    public static final String _GetCurrentTransportActions_ARG_InstanceID = "InstanceID";
    public static final String _GetCurrentTransportActions_ARG_Actions = "Actions";
    public static final String ACTION_SetAVTransportURI = "SetAVTransportURI";
    public static final String _SetAVTransportURI_ARG_InstanceID = "InstanceID";
    public static final String _SetAVTransportURI_ARG_CurrentURI = "CurrentURI";
    public static final String _SetAVTransportURI_ARG_CurrentURIMetaData = "CurrentURIMetaData";
    public static final String ACTION_GetPositionInfo = "GetPositionInfo";
    public static final String _GetPositionInfo_ARG_InstanceID = "InstanceID";
    public static final String _GetPositionInfo_ARG_Track = "Track";
    public static final String _GetPositionInfo_ARG_TrackDuration = "TrackDuration";
    public static final String _GetPositionInfo_ARG_TrackMetaData = "TrackMetaData";
    public static final String _GetPositionInfo_ARG_TrackURI = "TrackURI";
    public static final String _GetPositionInfo_ARG_RelTime = "RelTime";
    public static final String _GetPositionInfo_ARG_AbsTime = "AbsTime";
    public static final String _GetPositionInfo_ARG_RelCount = "RelCount";
    public static final String _GetPositionInfo_ARG_AbsCount = "AbsCount";
    public static final String ACTION_Stop = "Stop";
    public static final String _Stop_ARG_InstanceID = "InstanceID";
    public static final String ACTION_GetTransportSettings = "GetTransportSettings";
    public static final String _GetTransportSettings_ARG_InstanceID = "InstanceID";
    public static final String _GetTransportSettings_ARG_PlayMode = "PlayMode";
    public static final String _GetTransportSettings_ARG_RecQualityMode = "RecQualityMode";

    //-------------------------------------------------------
    // Property Name (30)
    //-------------------------------------------------------
    public static final String PROPERTY_PossibleRecordStorageMedia = "PossibleRecordStorageMedia";
    public static final String PROPERTY_AbsoluteTimePosition = "AbsoluteTimePosition";
    public static final String PROPERTY_NextAVTransportURI = "NextAVTransportURI";
    public static final String PROPERTY_CurrentTrackDuration = "CurrentTrackDuration";
    public static final String PROPERTY_TransportPlaySpeed = "TransportPlaySpeed";
    public static final String PROPERTY_TransportState = "TransportState";
    public static final String PROPERTY_PossiblePlaybackStorageMedia = "PossiblePlaybackStorageMedia";
    public static final String PROPERTY_A_ARG_TYPE_SeekTarget = "A_ARG_TYPE_SeekTarget";
    public static final String PROPERTY_AVTransportURIMetaData = "AVTransportURIMetaData";
    public static final String PROPERTY_A_ARG_TYPE_InstanceID = "A_ARG_TYPE_InstanceID";
    public static final String PROPERTY_CurrentTrackURI = "CurrentTrackURI";
    public static final String PROPERTY_NumberOfTracks = "NumberOfTracks";
    public static final String PROPERTY_CurrentPlayMode = "CurrentPlayMode";
    public static final String PROPERTY_RecordStorageMedium = "RecordStorageMedium";
    public static final String PROPERTY_TransportStatus = "TransportStatus";
    public static final String PROPERTY_AVTransportURI = "AVTransportURI";
    public static final String PROPERTY_RecordMediumWriteStatus = "RecordMediumWriteStatus";
    public static final String PROPERTY_CurrentTransportActions = "CurrentTransportActions";
    public static final String PROPERTY_PlaybackStorageMedium = "PlaybackStorageMedium";
    public static final String PROPERTY_CurrentTrack = "CurrentTrack";
    public static final String PROPERTY_RelativeTimePosition = "RelativeTimePosition";
    public static final String PROPERTY_AbsoluteCounterPosition = "AbsoluteCounterPosition";
    public static final String PROPERTY_CurrentMediaDuration = "CurrentMediaDuration";
    public static final String PROPERTY_CurrentTrackMetaData = "CurrentTrackMetaData";
    public static final String PROPERTY_NextAVTransportURIMetaData = "NextAVTransportURIMetaData";
    public static final String PROPERTY_RelativeCounterPosition = "RelativeCounterPosition";
    public static final String PROPERTY_PossibleRecordQualityModes = "PossibleRecordQualityModes";
    public static final String PROPERTY_A_ARG_TYPE_SeekMode = "A_ARG_TYPE_SeekMode";
    public static final String PROPERTY_CurrentRecordQualityMode = "CurrentRecordQualityMode";
    public static final String PROPERTY_LastChange = "LastChange";

    //-------------------------------------------------------
    // Property value defined (12)
    //-------------------------------------------------------

    public enum PossibleRecordStorageMedia {
        UNDEFINED,
        V_NOT_IMPLEMENTED;

        private static final String CONST_UNDEFINED = "UNDEFINED";
        private static final String CONST_V_NOT_IMPLEMENTED = "NOT_IMPLEMENTED";

        public static PossibleRecordStorageMedia retrieveType(String value) {
            if (value.equals(CONST_UNDEFINED)) {
                return UNDEFINED;
            }

            if (value.equals(CONST_V_NOT_IMPLEMENTED)) {
                return V_NOT_IMPLEMENTED;
            }

            return UNDEFINED;
        }

        public String getValue() {
            String value = null;
            switch (this) {
                case V_NOT_IMPLEMENTED:
                    value = CONST_V_NOT_IMPLEMENTED;
                    break;

                default:
                    break;
            }

            return value;
        }
    }

    public enum TransportPlaySpeed {
        UNDEFINED,
        V_1;

        private static final String CONST_UNDEFINED = "UNDEFINED";
        private static final String CONST_V_1 = "1";

        public static TransportPlaySpeed retrieveType(String value) {
            if (value.equals(CONST_UNDEFINED)) {
                return UNDEFINED;
            }

            if (value.equals(CONST_V_1)) {
                return V_1;
            }

            return UNDEFINED;
        }

        public String getValue() {
            String value = null;
            switch (this) {
                case V_1:
                    value = CONST_V_1;
                    break;

                default:
                    break;
            }

            return value;
        }
    }

    public enum TransportState {
        UNDEFINED,
        V_STOPPED,
        V_PAUSED_PLAYBACK,
        V_PLAYING,
        V_TRANSITIONING,
        V_NO_MEDIA_PRESENT;

        private static final String CONST_UNDEFINED = "UNDEFINED";
        private static final String CONST_V_STOPPED = "STOPPED";
        private static final String CONST_V_PAUSED_PLAYBACK = "PAUSED_PLAYBACK";
        private static final String CONST_V_PLAYING = "PLAYING";
        private static final String CONST_V_TRANSITIONING = "TRANSITIONING";
        private static final String CONST_V_NO_MEDIA_PRESENT = "NO_MEDIA_PRESENT";

        public static TransportState retrieveType(String value) {
            if (value.equals(CONST_UNDEFINED)) {
                return UNDEFINED;
            }

            if (value.equals(CONST_V_STOPPED)) {
                return V_STOPPED;
            }

            if (value.equals(CONST_V_PAUSED_PLAYBACK)) {
                return V_PAUSED_PLAYBACK;
            }

            if (value.equals(CONST_V_PLAYING)) {
                return V_PLAYING;
            }

            if (value.equals(CONST_V_TRANSITIONING)) {
                return V_TRANSITIONING;
            }

            if (value.equals(CONST_V_NO_MEDIA_PRESENT)) {
                return V_NO_MEDIA_PRESENT;
            }

            return UNDEFINED;
        }

        public String getValue() {
            String value = null;
            switch (this) {
                case V_STOPPED:
                    value = CONST_V_STOPPED;
                    break;

                case V_PAUSED_PLAYBACK:
                    value = CONST_V_PAUSED_PLAYBACK;
                    break;

                case V_PLAYING:
                    value = CONST_V_PLAYING;
                    break;

                case V_TRANSITIONING:
                    value = CONST_V_TRANSITIONING;
                    break;

                case V_NO_MEDIA_PRESENT:
                    value = CONST_V_NO_MEDIA_PRESENT;
                    break;

                default:
                    break;
            }

            return value;
        }
    }

    public enum PossiblePlaybackStorageMedia {
        UNDEFINED,
        V_UNKNOWN,
        V_CD_DA,
        V_DVD_VIDEO,
        V_HDD,
        V_NETWORK;

        private static final String CONST_UNDEFINED = "UNDEFINED";
        private static final String CONST_V_UNKNOWN = "UNKNOWN";
        private static final String CONST_V_CD_DA = "CD-DA";
        private static final String CONST_V_DVD_VIDEO = "DVD-VIDEO";
        private static final String CONST_V_HDD = "HDD";
        private static final String CONST_V_NETWORK = "NETWORK";

        public static PossiblePlaybackStorageMedia retrieveType(String value) {
            if (value.equals(CONST_UNDEFINED)) {
                return UNDEFINED;
            }

            if (value.equals(CONST_V_UNKNOWN)) {
                return V_UNKNOWN;
            }

            if (value.equals(CONST_V_CD_DA)) {
                return V_CD_DA;
            }

            if (value.equals(CONST_V_DVD_VIDEO)) {
                return V_DVD_VIDEO;
            }

            if (value.equals(CONST_V_HDD)) {
                return V_HDD;
            }

            if (value.equals(CONST_V_NETWORK)) {
                return V_NETWORK;
            }

            return UNDEFINED;
        }

        public String getValue() {
            String value = null;
            switch (this) {
                case V_UNKNOWN:
                    value = CONST_V_UNKNOWN;
                    break;

                case V_CD_DA:
                    value = CONST_V_CD_DA;
                    break;

                case V_DVD_VIDEO:
                    value = CONST_V_DVD_VIDEO;
                    break;

                case V_HDD:
                    value = CONST_V_HDD;
                    break;

                case V_NETWORK:
                    value = CONST_V_NETWORK;
                    break;

                default:
                    break;
            }

            return value;
        }
    }

    public enum CurrentPlayMode {
        UNDEFINED,
        V_NORMAL,
        V_SHUFFLE,
        V_REPEAT_ALL;

        private static final String CONST_UNDEFINED = "UNDEFINED";
        private static final String CONST_V_NORMAL = "NORMAL";
        private static final String CONST_V_SHUFFLE = "SHUFFLE";
        private static final String CONST_V_REPEAT_ALL = "REPEAT_ALL";

        public static CurrentPlayMode retrieveType(String value) {
            if (value.equals(CONST_UNDEFINED)) {
                return UNDEFINED;
            }

            if (value.equals(CONST_V_NORMAL)) {
                return V_NORMAL;
            }

            if (value.equals(CONST_V_SHUFFLE)) {
                return V_SHUFFLE;
            }

            if (value.equals(CONST_V_REPEAT_ALL)) {
                return V_REPEAT_ALL;
            }

            return UNDEFINED;
        }

        public String getValue() {
            String value = null;
            switch (this) {
                case V_NORMAL:
                    value = CONST_V_NORMAL;
                    break;

                case V_SHUFFLE:
                    value = CONST_V_SHUFFLE;
                    break;

                case V_REPEAT_ALL:
                    value = CONST_V_REPEAT_ALL;
                    break;

                default:
                    break;
            }

            return value;
        }
    }

    public enum RecordStorageMedium {
        UNDEFINED,
        V_NOT_IMPLEMENTED;

        private static final String CONST_UNDEFINED = "UNDEFINED";
        private static final String CONST_V_NOT_IMPLEMENTED = "NOT_IMPLEMENTED";

        public static RecordStorageMedium retrieveType(String value) {
            if (value.equals(CONST_UNDEFINED)) {
                return UNDEFINED;
            }

            if (value.equals(CONST_V_NOT_IMPLEMENTED)) {
                return V_NOT_IMPLEMENTED;
            }

            return UNDEFINED;
        }

        public String getValue() {
            String value = null;
            switch (this) {
                case V_NOT_IMPLEMENTED:
                    value = CONST_V_NOT_IMPLEMENTED;
                    break;

                default:
                    break;
            }

            return value;
        }
    }

    public enum TransportStatus {
        UNDEFINED,
        V_OK,
        V_ERROR_OCCURRED;

        private static final String CONST_UNDEFINED = "UNDEFINED";
        private static final String CONST_V_OK = "OK";
        private static final String CONST_V_ERROR_OCCURRED = "ERROR_OCCURRED";

        public static TransportStatus retrieveType(String value) {
            if (value.equals(CONST_UNDEFINED)) {
                return UNDEFINED;
            }

            if (value.equals(CONST_V_OK)) {
                return V_OK;
            }

            if (value.equals(CONST_V_ERROR_OCCURRED)) {
                return V_ERROR_OCCURRED;
            }

            return UNDEFINED;
        }

        public String getValue() {
            String value = null;
            switch (this) {
                case V_OK:
                    value = CONST_V_OK;
                    break;

                case V_ERROR_OCCURRED:
                    value = CONST_V_ERROR_OCCURRED;
                    break;

                default:
                    break;
            }

            return value;
        }
    }

    public enum RecordMediumWriteStatus {
        UNDEFINED,
        V_NOT_IMPLEMENTED;

        private static final String CONST_UNDEFINED = "UNDEFINED";
        private static final String CONST_V_NOT_IMPLEMENTED = "NOT_IMPLEMENTED";

        public static RecordMediumWriteStatus retrieveType(String value) {
            if (value.equals(CONST_UNDEFINED)) {
                return UNDEFINED;
            }

            if (value.equals(CONST_V_NOT_IMPLEMENTED)) {
                return V_NOT_IMPLEMENTED;
            }

            return UNDEFINED;
        }

        public String getValue() {
            String value = null;
            switch (this) {
                case V_NOT_IMPLEMENTED:
                    value = CONST_V_NOT_IMPLEMENTED;
                    break;

                default:
                    break;
            }

            return value;
        }
    }

    public enum PlaybackStorageMedium {
        UNDEFINED,
        V_UNKNOWN,
        V_CD_DA,
        V_DVD_VIDEO,
        V_HDD,
        V_NETWORK;

        private static final String CONST_UNDEFINED = "UNDEFINED";
        private static final String CONST_V_UNKNOWN = "UNKNOWN";
        private static final String CONST_V_CD_DA = "CD-DA";
        private static final String CONST_V_DVD_VIDEO = "DVD-VIDEO";
        private static final String CONST_V_HDD = "HDD";
        private static final String CONST_V_NETWORK = "NETWORK";

        public static PlaybackStorageMedium retrieveType(String value) {
            if (value.equals(CONST_UNDEFINED)) {
                return UNDEFINED;
            }

            if (value.equals(CONST_V_UNKNOWN)) {
                return V_UNKNOWN;
            }

            if (value.equals(CONST_V_CD_DA)) {
                return V_CD_DA;
            }

            if (value.equals(CONST_V_DVD_VIDEO)) {
                return V_DVD_VIDEO;
            }

            if (value.equals(CONST_V_HDD)) {
                return V_HDD;
            }

            if (value.equals(CONST_V_NETWORK)) {
                return V_NETWORK;
            }

            return UNDEFINED;
        }

        public String getValue() {
            String value = null;
            switch (this) {
                case V_UNKNOWN:
                    value = CONST_V_UNKNOWN;
                    break;

                case V_CD_DA:
                    value = CONST_V_CD_DA;
                    break;

                case V_DVD_VIDEO:
                    value = CONST_V_DVD_VIDEO;
                    break;

                case V_HDD:
                    value = CONST_V_HDD;
                    break;

                case V_NETWORK:
                    value = CONST_V_NETWORK;
                    break;

                default:
                    break;
            }

            return value;
        }
    }

    public enum PossibleRecordQualityModes {
        UNDEFINED,
        V_NOT_IMPLEMENTED;

        private static final String CONST_UNDEFINED = "UNDEFINED";
        private static final String CONST_V_NOT_IMPLEMENTED = "NOT_IMPLEMENTED";

        public static PossibleRecordQualityModes retrieveType(String value) {
            if (value.equals(CONST_UNDEFINED)) {
                return UNDEFINED;
            }

            if (value.equals(CONST_V_NOT_IMPLEMENTED)) {
                return V_NOT_IMPLEMENTED;
            }

            return UNDEFINED;
        }

        public String getValue() {
            String value = null;
            switch (this) {
                case V_NOT_IMPLEMENTED:
                    value = CONST_V_NOT_IMPLEMENTED;
                    break;

                default:
                    break;
            }

            return value;
        }
    }

    public enum A_ARG_TYPE_SeekMode {
        UNDEFINED,
        V_ABS_COUNT,
        V_TRACK_NR,
        V_REL_TIME;

        private static final String CONST_UNDEFINED = "UNDEFINED";
        private static final String CONST_V_ABS_COUNT = "ABS_COUNT";
        private static final String CONST_V_TRACK_NR = "TRACK_NR";
        private static final String CONST_V_REL_TIME = "REL_TIME";

        public static A_ARG_TYPE_SeekMode retrieveType(String value) {
            if (value.equals(CONST_UNDEFINED)) {
                return UNDEFINED;
            }

            if (value.equals(CONST_V_ABS_COUNT)) {
                return V_ABS_COUNT;
            }

            if (value.equals(CONST_V_TRACK_NR)) {
                return V_TRACK_NR;
            }

            if (value.equals(CONST_V_REL_TIME)) {
                return V_REL_TIME;
            }

            return UNDEFINED;
        }

        public String getValue() {
            String value = null;
            switch (this) {
                case V_ABS_COUNT:
                    value = CONST_V_ABS_COUNT;
                    break;

                case V_TRACK_NR:
                    value = CONST_V_TRACK_NR;
                    break;

                case V_REL_TIME:
                    value = CONST_V_REL_TIME;
                    break;

                default:
                    break;
            }

            return value;
        }
    }

    public enum CurrentRecordQualityMode {
        UNDEFINED,
        V_NOT_IMPLEMENTED;

        private static final String CONST_UNDEFINED = "UNDEFINED";
        private static final String CONST_V_NOT_IMPLEMENTED = "NOT_IMPLEMENTED";

        public static CurrentRecordQualityMode retrieveType(String value) {
            if (value.equals(CONST_UNDEFINED)) {
                return UNDEFINED;
            }

            if (value.equals(CONST_V_NOT_IMPLEMENTED)) {
                return V_NOT_IMPLEMENTED;
            }

            return UNDEFINED;
        }

        public String getValue() {
            String value = null;
            switch (this) {
                case V_NOT_IMPLEMENTED:
                    value = CONST_V_NOT_IMPLEMENTED;
                    break;

                default:
                    break;
            }

            return value;
        }
    }

    //-------------------------------------------------------
    // Action Result (13)
    //-------------------------------------------------------

    // Next has no Result

    // Seek has no Result

    // Play has no Result

    public class GetTransportInfo_Result {
        public TransportState theCurrentTransportState;
        public TransportStatus theCurrentTransportStatus;
        public TransportPlaySpeed theCurrentSpeed;
    }

    // Previous has no Result

    public class GetMediaInfo_Result {
        public Long theNrTracks;
        public String theMediaDuration;
        public String theCurrentURI;
        public String theCurrentURIMetaData;
        public String theNextURI;
        public String theNextURIMetaData;
        public PlaybackStorageMedium thePlayMedium;
        public RecordStorageMedium theRecordMedium;
        public RecordMediumWriteStatus theWriteStatus;
    }

    public class GetDeviceCapabilities_Result {
        public PossiblePlaybackStorageMedia thePlayMedia;
        public PossibleRecordStorageMedia theRecMedia;
        public PossibleRecordQualityModes theRecQualityModes;
    }

    // Pause has no Result

    public class GetCurrentTransportActions_Result {
        public String theActions;
    }

    // SetAVTransportURI has no Result

    public class GetPositionInfo_Result {
        public Long theTrack;
        public String theTrackDuration;
        public String theTrackMetaData;
        public String theTrackURI;
        public String theRelTime;
        public String theAbsTime;
        public Integer theRelCount;
        public Integer theAbsCount;
    }

    // Stop has no Result

    public class GetTransportSettings_Result {
        public CurrentPlayMode thePlayMode;
        public CurrentRecordQualityMode theRecQualityMode;
    }


    //-------------------------------------------------------
    // Action Handler (13)
    //-------------------------------------------------------

    public interface Handler {
        UpnpError onNext(Long theInstanceID);
        UpnpError onSeek(Long theInstanceID, A_ARG_TYPE_SeekMode theUnit, String theTarget);
        UpnpError onPlay(Long theInstanceID, TransportPlaySpeed theSpeed);
        UpnpError onGetTransportInfo(Long theInstanceID, GetTransportInfo_Result result);
        UpnpError onPrevious(Long theInstanceID);
        UpnpError onGetMediaInfo(Long theInstanceID, GetMediaInfo_Result result);
        UpnpError onGetDeviceCapabilities(Long theInstanceID, GetDeviceCapabilities_Result result);
        UpnpError onPause(Long theInstanceID);
        UpnpError onGetCurrentTransportActions(Long theInstanceID, GetCurrentTransportActions_Result result);
        UpnpError onSetAVTransportURI(Long theInstanceID, String theCurrentURI, String theCurrentURIMetaData);
        UpnpError onGetPositionInfo(Long theInstanceID, GetPositionInfo_Result result);
        UpnpError onStop(Long theInstanceID);
        UpnpError onGetTransportSettings(Long theInstanceID, GetTransportSettings_Result result);
    }

    private UpnpError handle_Next(ActionInfo info) {
        Long theInstanceID = (Long)info.getArgumentValue(_Next_ARG_InstanceID);

        UpnpError error = _handler.onNext(theInstanceID);
        if (! error.equals(UpnpError.OK)) {
            return error;
        }

        return UpnpError.OK;
    }

    private UpnpError handle_Seek(ActionInfo info) {
        Long theInstanceID = (Long)info.getArgumentValue(_Seek_ARG_InstanceID);
        A_ARG_TYPE_SeekMode theUnit = A_ARG_TYPE_SeekMode.retrieveType((String)info.getArgumentValue(_Seek_ARG_Unit));
        String theTarget = (String)info.getArgumentValue(_Seek_ARG_Target);

        UpnpError error = _handler.onSeek(theInstanceID, theUnit, theTarget);
        if (! error.equals(UpnpError.OK)) {
            return error;
        }

        return UpnpError.OK;
    }

    private UpnpError handle_Play(ActionInfo info) {
        Long theInstanceID = (Long)info.getArgumentValue(_Play_ARG_InstanceID);
        TransportPlaySpeed theSpeed = TransportPlaySpeed.retrieveType((String)info.getArgumentValue(_Play_ARG_Speed));

        UpnpError error = _handler.onPlay(theInstanceID, theSpeed);
        if (! error.equals(UpnpError.OK)) {
            return error;
        }

        return UpnpError.OK;
    }

    private UpnpError handle_GetTransportInfo(ActionInfo info) {
        Long theInstanceID = (Long)info.getArgumentValue(_GetTransportInfo_ARG_InstanceID);
        GetTransportInfo_Result result = new GetTransportInfo_Result();

        UpnpError error = _handler.onGetTransportInfo(theInstanceID, result);
        if (! error.equals(UpnpError.OK)) {
            return error;
        }

        if (! info.setArgumentValue(_GetTransportInfo_ARG_CurrentTransportState, result.theCurrentTransportState.getValue(), Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        if (! info.setArgumentValue(_GetTransportInfo_ARG_CurrentTransportStatus, result.theCurrentTransportStatus.getValue(), Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        if (! info.setArgumentValue(_GetTransportInfo_ARG_CurrentSpeed, result.theCurrentSpeed.getValue(), Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        return UpnpError.OK;
    }

    private UpnpError handle_Previous(ActionInfo info) {
        Long theInstanceID = (Long)info.getArgumentValue(_Previous_ARG_InstanceID);

        UpnpError error = _handler.onPrevious(theInstanceID);
        if (! error.equals(UpnpError.OK)) {
            return error;
        }

        return UpnpError.OK;
    }

    private UpnpError handle_GetMediaInfo(ActionInfo info) {
        Long theInstanceID = (Long)info.getArgumentValue(_GetMediaInfo_ARG_InstanceID);
        GetMediaInfo_Result result = new GetMediaInfo_Result();

        UpnpError error = _handler.onGetMediaInfo(theInstanceID, result);
        if (! error.equals(UpnpError.OK)) {
            return error;
        }

        if (! info.setArgumentValue(_GetMediaInfo_ARG_NrTracks, result.theNrTracks, Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        if (! info.setArgumentValue(_GetMediaInfo_ARG_MediaDuration, result.theMediaDuration, Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        if (! info.setArgumentValue(_GetMediaInfo_ARG_CurrentURI, result.theCurrentURI, Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        if (! info.setArgumentValue(_GetMediaInfo_ARG_CurrentURIMetaData, result.theCurrentURIMetaData, Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        if (! info.setArgumentValue(_GetMediaInfo_ARG_NextURI, result.theNextURI, Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        if (! info.setArgumentValue(_GetMediaInfo_ARG_NextURIMetaData, result.theNextURIMetaData, Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        if (! info.setArgumentValue(_GetMediaInfo_ARG_PlayMedium, result.thePlayMedium.getValue(), Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        if (! info.setArgumentValue(_GetMediaInfo_ARG_RecordMedium, result.theRecordMedium.getValue(), Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        if (! info.setArgumentValue(_GetMediaInfo_ARG_WriteStatus, result.theWriteStatus.getValue(), Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        return UpnpError.OK;
    }

    private UpnpError handle_GetDeviceCapabilities(ActionInfo info) {
        Long theInstanceID = (Long)info.getArgumentValue(_GetDeviceCapabilities_ARG_InstanceID);
        GetDeviceCapabilities_Result result = new GetDeviceCapabilities_Result();

        UpnpError error = _handler.onGetDeviceCapabilities(theInstanceID, result);
        if (! error.equals(UpnpError.OK)) {
            return error;
        }

        if (! info.setArgumentValue(_GetDeviceCapabilities_ARG_PlayMedia, result.thePlayMedia.getValue(), Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        if (! info.setArgumentValue(_GetDeviceCapabilities_ARG_RecMedia, result.theRecMedia.getValue(), Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        if (! info.setArgumentValue(_GetDeviceCapabilities_ARG_RecQualityModes, result.theRecQualityModes.getValue(), Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        return UpnpError.OK;
    }

    private UpnpError handle_Pause(ActionInfo info) {
        Long theInstanceID = (Long)info.getArgumentValue(_Pause_ARG_InstanceID);

        UpnpError error = _handler.onPause(theInstanceID);
        if (! error.equals(UpnpError.OK)) {
            return error;
        }

        return UpnpError.OK;
    }

    private UpnpError handle_GetCurrentTransportActions(ActionInfo info) {
        Long theInstanceID = (Long)info.getArgumentValue(_GetCurrentTransportActions_ARG_InstanceID);
        GetCurrentTransportActions_Result result = new GetCurrentTransportActions_Result();

        UpnpError error = _handler.onGetCurrentTransportActions(theInstanceID, result);
        if (! error.equals(UpnpError.OK)) {
            return error;
        }

        if (! info.setArgumentValue(_GetCurrentTransportActions_ARG_Actions, result.theActions, Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        return UpnpError.OK;
    }

    private UpnpError handle_SetAVTransportURI(ActionInfo info) {
        Long theInstanceID = (Long)info.getArgumentValue(_SetAVTransportURI_ARG_InstanceID);
        String theCurrentURI = (String)info.getArgumentValue(_SetAVTransportURI_ARG_CurrentURI);
        String theCurrentURIMetaData = (String)info.getArgumentValue(_SetAVTransportURI_ARG_CurrentURIMetaData);

        UpnpError error = _handler.onSetAVTransportURI(theInstanceID, theCurrentURI, theCurrentURIMetaData);
        if (! error.equals(UpnpError.OK)) {
            return error;
        }

        return UpnpError.OK;
    }

    private UpnpError handle_GetPositionInfo(ActionInfo info) {
        Long theInstanceID = (Long)info.getArgumentValue(_GetPositionInfo_ARG_InstanceID);
        GetPositionInfo_Result result = new GetPositionInfo_Result();

        UpnpError error = _handler.onGetPositionInfo(theInstanceID, result);
        if (! error.equals(UpnpError.OK)) {
            return error;
        }

        if (! info.setArgumentValue(_GetPositionInfo_ARG_Track, result.theTrack, Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        if (! info.setArgumentValue(_GetPositionInfo_ARG_TrackDuration, result.theTrackDuration, Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        if (! info.setArgumentValue(_GetPositionInfo_ARG_TrackMetaData, result.theTrackMetaData, Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        if (! info.setArgumentValue(_GetPositionInfo_ARG_TrackURI, result.theTrackURI, Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        if (! info.setArgumentValue(_GetPositionInfo_ARG_RelTime, result.theRelTime, Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        if (! info.setArgumentValue(_GetPositionInfo_ARG_AbsTime, result.theAbsTime, Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        if (! info.setArgumentValue(_GetPositionInfo_ARG_RelCount, result.theRelCount, Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        if (! info.setArgumentValue(_GetPositionInfo_ARG_AbsCount, result.theAbsCount, Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        return UpnpError.OK;
    }

    private UpnpError handle_Stop(ActionInfo info) {
        Long theInstanceID = (Long)info.getArgumentValue(_Stop_ARG_InstanceID);

        UpnpError error = _handler.onStop(theInstanceID);
        if (! error.equals(UpnpError.OK)) {
            return error;
        }

        return UpnpError.OK;
    }

    private UpnpError handle_GetTransportSettings(ActionInfo info) {
        Long theInstanceID = (Long)info.getArgumentValue(_GetTransportSettings_ARG_InstanceID);
        GetTransportSettings_Result result = new GetTransportSettings_Result();

        UpnpError error = _handler.onGetTransportSettings(theInstanceID, result);
        if (! error.equals(UpnpError.OK)) {
            return error;
        }

        if (! info.setArgumentValue(_GetTransportSettings_ARG_PlayMode, result.thePlayMode.getValue(), Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        if (! info.setArgumentValue(_GetTransportSettings_ARG_RecQualityMode, result.theRecQualityMode.getValue(), Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        return UpnpError.OK;
    }

    //-------------------------------------------------------
    // Method
    //-------------------------------------------------------

    private Service _service;
    private Handler _handler;

    public AVTransport(Device device) {
        _service = new Service(SERVICE_TYPE);
        _service.setServiceId(toServiceId(SERVICE_TYPE));
        _service.setScpdUrl(toScpdUrl(device.getDeviceId(), SERVICE_TYPE));
        _service.setControlUrl(toCtrlUrl(device.getDeviceId(), SERVICE_TYPE));
        _service.setEventSubUrl(toEventUrl(device.getDeviceId(), SERVICE_TYPE));

        Action _Next = new Action(ACTION_Next);
        _Next.addArgument(new Argument(_Next_ARG_InstanceID, Argument.Direction.IN, PROPERTY_A_ARG_TYPE_InstanceID));
        _service.addAction(_Next);

        Action _Seek = new Action(ACTION_Seek);
        _Seek.addArgument(new Argument(_Seek_ARG_InstanceID, Argument.Direction.IN, PROPERTY_A_ARG_TYPE_InstanceID));
        _Seek.addArgument(new Argument(_Seek_ARG_Unit, Argument.Direction.IN, PROPERTY_A_ARG_TYPE_SeekMode));
        _Seek.addArgument(new Argument(_Seek_ARG_Target, Argument.Direction.IN, PROPERTY_A_ARG_TYPE_SeekTarget));
        _service.addAction(_Seek);

        Action _Play = new Action(ACTION_Play);
        _Play.addArgument(new Argument(_Play_ARG_InstanceID, Argument.Direction.IN, PROPERTY_A_ARG_TYPE_InstanceID));
        _Play.addArgument(new Argument(_Play_ARG_Speed, Argument.Direction.IN, PROPERTY_TransportPlaySpeed));
        _service.addAction(_Play);

        Action _GetTransportInfo = new Action(ACTION_GetTransportInfo);
        _GetTransportInfo.addArgument(new Argument(_GetTransportInfo_ARG_InstanceID, Argument.Direction.IN, PROPERTY_A_ARG_TYPE_InstanceID));
        _GetTransportInfo.addArgument(new Argument(_GetTransportInfo_ARG_CurrentTransportState, Argument.Direction.OUT, PROPERTY_TransportState));
        _GetTransportInfo.addArgument(new Argument(_GetTransportInfo_ARG_CurrentTransportStatus, Argument.Direction.OUT, PROPERTY_TransportStatus));
        _GetTransportInfo.addArgument(new Argument(_GetTransportInfo_ARG_CurrentSpeed, Argument.Direction.OUT, PROPERTY_TransportPlaySpeed));
        _service.addAction(_GetTransportInfo);

        Action _Previous = new Action(ACTION_Previous);
        _Previous.addArgument(new Argument(_Previous_ARG_InstanceID, Argument.Direction.IN, PROPERTY_A_ARG_TYPE_InstanceID));
        _service.addAction(_Previous);

        Action _GetMediaInfo = new Action(ACTION_GetMediaInfo);
        _GetMediaInfo.addArgument(new Argument(_GetMediaInfo_ARG_InstanceID, Argument.Direction.IN, PROPERTY_A_ARG_TYPE_InstanceID));
        _GetMediaInfo.addArgument(new Argument(_GetMediaInfo_ARG_NrTracks, Argument.Direction.OUT, PROPERTY_NumberOfTracks));
        _GetMediaInfo.addArgument(new Argument(_GetMediaInfo_ARG_MediaDuration, Argument.Direction.OUT, PROPERTY_CurrentMediaDuration));
        _GetMediaInfo.addArgument(new Argument(_GetMediaInfo_ARG_CurrentURI, Argument.Direction.OUT, PROPERTY_AVTransportURI));
        _GetMediaInfo.addArgument(new Argument(_GetMediaInfo_ARG_CurrentURIMetaData, Argument.Direction.OUT, PROPERTY_AVTransportURIMetaData));
        _GetMediaInfo.addArgument(new Argument(_GetMediaInfo_ARG_NextURI, Argument.Direction.OUT, PROPERTY_NextAVTransportURI));
        _GetMediaInfo.addArgument(new Argument(_GetMediaInfo_ARG_NextURIMetaData, Argument.Direction.OUT, PROPERTY_NextAVTransportURIMetaData));
        _GetMediaInfo.addArgument(new Argument(_GetMediaInfo_ARG_PlayMedium, Argument.Direction.OUT, PROPERTY_PlaybackStorageMedium));
        _GetMediaInfo.addArgument(new Argument(_GetMediaInfo_ARG_RecordMedium, Argument.Direction.OUT, PROPERTY_RecordStorageMedium));
        _GetMediaInfo.addArgument(new Argument(_GetMediaInfo_ARG_WriteStatus, Argument.Direction.OUT, PROPERTY_RecordMediumWriteStatus));
        _service.addAction(_GetMediaInfo);

        Action _GetDeviceCapabilities = new Action(ACTION_GetDeviceCapabilities);
        _GetDeviceCapabilities.addArgument(new Argument(_GetDeviceCapabilities_ARG_InstanceID, Argument.Direction.IN, PROPERTY_A_ARG_TYPE_InstanceID));
        _GetDeviceCapabilities.addArgument(new Argument(_GetDeviceCapabilities_ARG_PlayMedia, Argument.Direction.OUT, PROPERTY_PossiblePlaybackStorageMedia));
        _GetDeviceCapabilities.addArgument(new Argument(_GetDeviceCapabilities_ARG_RecMedia, Argument.Direction.OUT, PROPERTY_PossibleRecordStorageMedia));
        _GetDeviceCapabilities.addArgument(new Argument(_GetDeviceCapabilities_ARG_RecQualityModes, Argument.Direction.OUT, PROPERTY_PossibleRecordQualityModes));
        _service.addAction(_GetDeviceCapabilities);

        Action _Pause = new Action(ACTION_Pause);
        _Pause.addArgument(new Argument(_Pause_ARG_InstanceID, Argument.Direction.IN, PROPERTY_A_ARG_TYPE_InstanceID));
        _service.addAction(_Pause);

        Action _GetCurrentTransportActions = new Action(ACTION_GetCurrentTransportActions);
        _GetCurrentTransportActions.addArgument(new Argument(_GetCurrentTransportActions_ARG_InstanceID, Argument.Direction.IN, PROPERTY_A_ARG_TYPE_InstanceID));
        _GetCurrentTransportActions.addArgument(new Argument(_GetCurrentTransportActions_ARG_Actions, Argument.Direction.OUT, PROPERTY_CurrentTransportActions));
        _service.addAction(_GetCurrentTransportActions);

        Action _SetAVTransportURI = new Action(ACTION_SetAVTransportURI);
        _SetAVTransportURI.addArgument(new Argument(_SetAVTransportURI_ARG_InstanceID, Argument.Direction.IN, PROPERTY_A_ARG_TYPE_InstanceID));
        _SetAVTransportURI.addArgument(new Argument(_SetAVTransportURI_ARG_CurrentURI, Argument.Direction.IN, PROPERTY_AVTransportURI));
        _SetAVTransportURI.addArgument(new Argument(_SetAVTransportURI_ARG_CurrentURIMetaData, Argument.Direction.IN, PROPERTY_AVTransportURIMetaData));
        _service.addAction(_SetAVTransportURI);

        Action _GetPositionInfo = new Action(ACTION_GetPositionInfo);
        _GetPositionInfo.addArgument(new Argument(_GetPositionInfo_ARG_InstanceID, Argument.Direction.IN, PROPERTY_A_ARG_TYPE_InstanceID));
        _GetPositionInfo.addArgument(new Argument(_GetPositionInfo_ARG_Track, Argument.Direction.OUT, PROPERTY_CurrentTrack));
        _GetPositionInfo.addArgument(new Argument(_GetPositionInfo_ARG_TrackDuration, Argument.Direction.OUT, PROPERTY_CurrentTrackDuration));
        _GetPositionInfo.addArgument(new Argument(_GetPositionInfo_ARG_TrackMetaData, Argument.Direction.OUT, PROPERTY_CurrentTrackMetaData));
        _GetPositionInfo.addArgument(new Argument(_GetPositionInfo_ARG_TrackURI, Argument.Direction.OUT, PROPERTY_CurrentTrackURI));
        _GetPositionInfo.addArgument(new Argument(_GetPositionInfo_ARG_RelTime, Argument.Direction.OUT, PROPERTY_RelativeTimePosition));
        _GetPositionInfo.addArgument(new Argument(_GetPositionInfo_ARG_AbsTime, Argument.Direction.OUT, PROPERTY_AbsoluteTimePosition));
        _GetPositionInfo.addArgument(new Argument(_GetPositionInfo_ARG_RelCount, Argument.Direction.OUT, PROPERTY_RelativeCounterPosition));
        _GetPositionInfo.addArgument(new Argument(_GetPositionInfo_ARG_AbsCount, Argument.Direction.OUT, PROPERTY_AbsoluteCounterPosition));
        _service.addAction(_GetPositionInfo);

        Action _Stop = new Action(ACTION_Stop);
        _Stop.addArgument(new Argument(_Stop_ARG_InstanceID, Argument.Direction.IN, PROPERTY_A_ARG_TYPE_InstanceID));
        _service.addAction(_Stop);

        Action _GetTransportSettings = new Action(ACTION_GetTransportSettings);
        _GetTransportSettings.addArgument(new Argument(_GetTransportSettings_ARG_InstanceID, Argument.Direction.IN, PROPERTY_A_ARG_TYPE_InstanceID));
        _GetTransportSettings.addArgument(new Argument(_GetTransportSettings_ARG_PlayMode, Argument.Direction.OUT, PROPERTY_CurrentPlayMode));
        _GetTransportSettings.addArgument(new Argument(_GetTransportSettings_ARG_RecQualityMode, Argument.Direction.OUT, PROPERTY_CurrentRecordQualityMode));
        _service.addAction(_GetTransportSettings);

        PropertyDefinition _PossibleRecordStorageMedia = new PropertyDefinition(PROPERTY_PossibleRecordStorageMedia, DataType.STRING, false);
        AllowedValueList _PossibleRecordStorageMedia_list = new AllowedValueList(DataType.STRING);
        _PossibleRecordStorageMedia_list.appendAllowedValue("NOT_IMPLEMENTED");
        _PossibleRecordStorageMedia.setAllowedValueList(_PossibleRecordStorageMedia_list);
        _service.addProperty(_PossibleRecordStorageMedia);

        PropertyDefinition _AbsoluteTimePosition = new PropertyDefinition(PROPERTY_AbsoluteTimePosition, DataType.STRING, false);
        _service.addProperty(_AbsoluteTimePosition);

        PropertyDefinition _NextAVTransportURI = new PropertyDefinition(PROPERTY_NextAVTransportURI, DataType.STRING, false);
        _service.addProperty(_NextAVTransportURI);

        PropertyDefinition _CurrentTrackDuration = new PropertyDefinition(PROPERTY_CurrentTrackDuration, DataType.STRING, false);
        _service.addProperty(_CurrentTrackDuration);

        PropertyDefinition _TransportPlaySpeed = new PropertyDefinition(PROPERTY_TransportPlaySpeed, DataType.STRING, false);
        AllowedValueList _TransportPlaySpeed_list = new AllowedValueList(DataType.STRING);
        _TransportPlaySpeed_list.appendAllowedValue("1");
        _TransportPlaySpeed.setAllowedValueList(_TransportPlaySpeed_list);
        _service.addProperty(_TransportPlaySpeed);

        PropertyDefinition _TransportState = new PropertyDefinition(PROPERTY_TransportState, DataType.STRING, false);
        AllowedValueList _TransportState_list = new AllowedValueList(DataType.STRING);
        _TransportState_list.appendAllowedValue("STOPPED");
        _TransportState_list.appendAllowedValue("PAUSED_PLAYBACK");
        _TransportState_list.appendAllowedValue("PLAYING");
        _TransportState_list.appendAllowedValue("TRANSITIONING");
        _TransportState_list.appendAllowedValue("NO_MEDIA_PRESENT");
        _TransportState.setAllowedValueList(_TransportState_list);
        _service.addProperty(_TransportState);

        PropertyDefinition _PossiblePlaybackStorageMedia = new PropertyDefinition(PROPERTY_PossiblePlaybackStorageMedia, DataType.STRING, false);
        AllowedValueList _PossiblePlaybackStorageMedia_list = new AllowedValueList(DataType.STRING);
        _PossiblePlaybackStorageMedia_list.appendAllowedValue("UNKNOWN");
        _PossiblePlaybackStorageMedia_list.appendAllowedValue("CD-DA");
        _PossiblePlaybackStorageMedia_list.appendAllowedValue("DVD-VIDEO");
        _PossiblePlaybackStorageMedia_list.appendAllowedValue("HDD");
        _PossiblePlaybackStorageMedia_list.appendAllowedValue("NETWORK");
        _PossiblePlaybackStorageMedia.setAllowedValueList(_PossiblePlaybackStorageMedia_list);
        _service.addProperty(_PossiblePlaybackStorageMedia);

        PropertyDefinition _A_ARG_TYPE_SeekTarget = new PropertyDefinition(PROPERTY_A_ARG_TYPE_SeekTarget, DataType.STRING, false);
        _service.addProperty(_A_ARG_TYPE_SeekTarget);

        PropertyDefinition _AVTransportURIMetaData = new PropertyDefinition(PROPERTY_AVTransportURIMetaData, DataType.STRING, false);
        _service.addProperty(_AVTransportURIMetaData);

        PropertyDefinition _A_ARG_TYPE_InstanceID = new PropertyDefinition(PROPERTY_A_ARG_TYPE_InstanceID, DataType.UI4, false);
        _service.addProperty(_A_ARG_TYPE_InstanceID);

        PropertyDefinition _CurrentTrackURI = new PropertyDefinition(PROPERTY_CurrentTrackURI, DataType.STRING, false);
        _service.addProperty(_CurrentTrackURI);

        PropertyDefinition _NumberOfTracks = new PropertyDefinition(PROPERTY_NumberOfTracks, DataType.UI4, false);
        _NumberOfTracks.setAllowedValueRange(AllowedValueRange.create(DataType.UI4, 0, 65535));
        _service.addProperty(_NumberOfTracks);

        PropertyDefinition _CurrentPlayMode = new PropertyDefinition(PROPERTY_CurrentPlayMode, DataType.STRING, false);
        AllowedValueList _CurrentPlayMode_list = new AllowedValueList(DataType.STRING);
        _CurrentPlayMode_list.appendAllowedValue("NORMAL");
        _CurrentPlayMode_list.appendAllowedValue("SHUFFLE");
        _CurrentPlayMode_list.appendAllowedValue("REPEAT_ALL");
        _CurrentPlayMode.setAllowedValueList(_CurrentPlayMode_list);
        _service.addProperty(_CurrentPlayMode);

        PropertyDefinition _RecordStorageMedium = new PropertyDefinition(PROPERTY_RecordStorageMedium, DataType.STRING, false);
        AllowedValueList _RecordStorageMedium_list = new AllowedValueList(DataType.STRING);
        _RecordStorageMedium_list.appendAllowedValue("NOT_IMPLEMENTED");
        _RecordStorageMedium.setAllowedValueList(_RecordStorageMedium_list);
        _service.addProperty(_RecordStorageMedium);

        PropertyDefinition _TransportStatus = new PropertyDefinition(PROPERTY_TransportStatus, DataType.STRING, false);
        AllowedValueList _TransportStatus_list = new AllowedValueList(DataType.STRING);
        _TransportStatus_list.appendAllowedValue("OK");
        _TransportStatus_list.appendAllowedValue("ERROR_OCCURRED");
        _TransportStatus.setAllowedValueList(_TransportStatus_list);
        _service.addProperty(_TransportStatus);

        PropertyDefinition _AVTransportURI = new PropertyDefinition(PROPERTY_AVTransportURI, DataType.STRING, false);
        _service.addProperty(_AVTransportURI);

        PropertyDefinition _RecordMediumWriteStatus = new PropertyDefinition(PROPERTY_RecordMediumWriteStatus, DataType.STRING, false);
        AllowedValueList _RecordMediumWriteStatus_list = new AllowedValueList(DataType.STRING);
        _RecordMediumWriteStatus_list.appendAllowedValue("NOT_IMPLEMENTED");
        _RecordMediumWriteStatus.setAllowedValueList(_RecordMediumWriteStatus_list);
        _service.addProperty(_RecordMediumWriteStatus);

        PropertyDefinition _CurrentTransportActions = new PropertyDefinition(PROPERTY_CurrentTransportActions, DataType.STRING, false);
        _service.addProperty(_CurrentTransportActions);

        PropertyDefinition _PlaybackStorageMedium = new PropertyDefinition(PROPERTY_PlaybackStorageMedium, DataType.STRING, false);
        AllowedValueList _PlaybackStorageMedium_list = new AllowedValueList(DataType.STRING);
        _PlaybackStorageMedium_list.appendAllowedValue("UNKNOWN");
        _PlaybackStorageMedium_list.appendAllowedValue("CD-DA");
        _PlaybackStorageMedium_list.appendAllowedValue("DVD-VIDEO");
        _PlaybackStorageMedium_list.appendAllowedValue("HDD");
        _PlaybackStorageMedium_list.appendAllowedValue("NETWORK");
        _PlaybackStorageMedium.setAllowedValueList(_PlaybackStorageMedium_list);
        _service.addProperty(_PlaybackStorageMedium);

        PropertyDefinition _CurrentTrack = new PropertyDefinition(PROPERTY_CurrentTrack, DataType.UI4, false);
        _CurrentTrack.setAllowedValueRange(AllowedValueRange.create(DataType.UI4, 0, 65535));
        _service.addProperty(_CurrentTrack);

        PropertyDefinition _RelativeTimePosition = new PropertyDefinition(PROPERTY_RelativeTimePosition, DataType.STRING, false);
        _service.addProperty(_RelativeTimePosition);

        PropertyDefinition _AbsoluteCounterPosition = new PropertyDefinition(PROPERTY_AbsoluteCounterPosition, DataType.I4, false);
        _service.addProperty(_AbsoluteCounterPosition);

        PropertyDefinition _CurrentMediaDuration = new PropertyDefinition(PROPERTY_CurrentMediaDuration, DataType.STRING, false);
        _service.addProperty(_CurrentMediaDuration);

        PropertyDefinition _CurrentTrackMetaData = new PropertyDefinition(PROPERTY_CurrentTrackMetaData, DataType.STRING, false);
        _service.addProperty(_CurrentTrackMetaData);

        PropertyDefinition _NextAVTransportURIMetaData = new PropertyDefinition(PROPERTY_NextAVTransportURIMetaData, DataType.STRING, false);
        _service.addProperty(_NextAVTransportURIMetaData);

        PropertyDefinition _RelativeCounterPosition = new PropertyDefinition(PROPERTY_RelativeCounterPosition, DataType.I4, false);
        _service.addProperty(_RelativeCounterPosition);

        PropertyDefinition _PossibleRecordQualityModes = new PropertyDefinition(PROPERTY_PossibleRecordQualityModes, DataType.STRING, false);
        AllowedValueList _PossibleRecordQualityModes_list = new AllowedValueList(DataType.STRING);
        _PossibleRecordQualityModes_list.appendAllowedValue("NOT_IMPLEMENTED");
        _PossibleRecordQualityModes.setAllowedValueList(_PossibleRecordQualityModes_list);
        _service.addProperty(_PossibleRecordQualityModes);

        PropertyDefinition _A_ARG_TYPE_SeekMode = new PropertyDefinition(PROPERTY_A_ARG_TYPE_SeekMode, DataType.STRING, false);
        AllowedValueList _A_ARG_TYPE_SeekMode_list = new AllowedValueList(DataType.STRING);
        _A_ARG_TYPE_SeekMode_list.appendAllowedValue("ABS_COUNT");
        _A_ARG_TYPE_SeekMode_list.appendAllowedValue("TRACK_NR");
        _A_ARG_TYPE_SeekMode_list.appendAllowedValue("REL_TIME");
        _A_ARG_TYPE_SeekMode.setAllowedValueList(_A_ARG_TYPE_SeekMode_list);
        _service.addProperty(_A_ARG_TYPE_SeekMode);

        PropertyDefinition _CurrentRecordQualityMode = new PropertyDefinition(PROPERTY_CurrentRecordQualityMode, DataType.STRING, false);
        AllowedValueList _CurrentRecordQualityMode_list = new AllowedValueList(DataType.STRING);
        _CurrentRecordQualityMode_list.appendAllowedValue("NOT_IMPLEMENTED");
        _CurrentRecordQualityMode.setAllowedValueList(_CurrentRecordQualityMode_list);
        _service.addProperty(_CurrentRecordQualityMode);

        PropertyDefinition _LastChange = new PropertyDefinition(PROPERTY_LastChange, DataType.STRING, true);
        _service.addProperty(_LastChange);

        device.addService(_service);
    }

    public void setHandler(Handler handler) {
        _handler = handler;
    }

    @Override
    public UpnpError onAction(ActionInfo info) {
        if (_handler == null) {
           Log.e(TAG, "handler is null");
           return UpnpError.UPNP_ACTION_NOT_IMPLEMENTED;
        }

        if (info.getAction().getName().equals(ACTION_Next)) {
            return handle_Next(info);
        }

        if (info.getAction().getName().equals(ACTION_Seek)) {
            return handle_Seek(info);
        }

        if (info.getAction().getName().equals(ACTION_Play)) {
            return handle_Play(info);
        }

        if (info.getAction().getName().equals(ACTION_GetTransportInfo)) {
            return handle_GetTransportInfo(info);
        }

        if (info.getAction().getName().equals(ACTION_Previous)) {
            return handle_Previous(info);
        }

        if (info.getAction().getName().equals(ACTION_GetMediaInfo)) {
            return handle_GetMediaInfo(info);
        }

        if (info.getAction().getName().equals(ACTION_GetDeviceCapabilities)) {
            return handle_GetDeviceCapabilities(info);
        }

        if (info.getAction().getName().equals(ACTION_Pause)) {
            return handle_Pause(info);
        }

        if (info.getAction().getName().equals(ACTION_GetCurrentTransportActions)) {
            return handle_GetCurrentTransportActions(info);
        }

        if (info.getAction().getName().equals(ACTION_SetAVTransportURI)) {
            return handle_SetAVTransportURI(info);
        }

        if (info.getAction().getName().equals(ACTION_GetPositionInfo)) {
            return handle_GetPositionInfo(info);
        }

        if (info.getAction().getName().equals(ACTION_Stop)) {
            return handle_Stop(info);
        }

        if (info.getAction().getName().equals(ACTION_GetTransportSettings)) {
            return handle_GetTransportSettings(info);
        }

        return UpnpError.UPNP_ACTION_NOT_IMPLEMENTED;
    }

    public void sendEvents() {
        EventInfo info = EventInfoCreator.create(_service);

        try {
            UpnpManager.getHost().sendEvents(info);
        } catch (UpnpException e) {
            e.printStackTrace();
        }
    }

    public void setLastChange(String theLastChange) {
         _service.setPropertyValue(PROPERTY_LastChange, theLastChange);
    }

}
