/* Automatic generated by DeviceToC */

#include "tiny_memory.h"
#include "tiny_log.h"
#include "BleGateway.h"

#define TAG "BleGateway"

static const char * _ID_BleOperation = "urn:upnp-org:serviceId:BleOperation";

static TinyRet BleGateway_Construct(BleGateway *thiz, UpnpDeviceConfig *config, UpnpRuntime *runtime);
static void BleGateway_Dispose(BleGateway *thiz);
static UpnpCode action_handler(UpnpAction *action, void *ctx);

struct _BleGateway {
    UpnpDevice *device;
    UpnpRuntime *runtime;
    BleOperation *_BleOperation;
};

BleGateway * BleGateway_New(UpnpDeviceConfig *config, UpnpRuntime *runtime) {
    BleGateway * thiz = NULL;

    RETURN_VAL_IF_FAIL(config, NULL);
    RETURN_VAL_IF_FAIL(runtime, NULL);

    do {
        thiz = (BleGateway *)tiny_malloc(sizeof(BleGateway));
        if (thiz == NULL) {
            LOG_E(TAG, "OUT OF MEMORY!");
            break;
        }

        if (RET_FAILED(BleGateway_Construct(thiz, config, runtime))) {
            LOG_E(TAG, "BleGateway_Construct failed");
            BleGateway_Delete(thiz);
            thiz = NULL;
            break;
        }
    } while (0);

    return thiz;
}

static TinyRet BleGateway_Construct(BleGateway *thiz, UpnpDeviceConfig *config, UpnpRuntime *runtime) {
    TinyRet ret = TINY_RET_OK;

    RETURN_VAL_IF_FAIL(thiz, TINY_RET_E_ARG_NULL);
    RETURN_VAL_IF_FAIL(config, NULL);
    RETURN_VAL_IF_FAIL(runtime, NULL);

    do {
        memset(thiz, 0, sizeof(BleGateway));
        thiz->runtime = runtime;
        thiz->device = UpnpDeviceConfig_CreateDevice(config, BLEGATEWAY_DEVICE_TYPE);
        if (thiz->device == NULL) {
            LOG_E(TAG, "UpnpDeviceConfig_CreateDevice failed");
            ret = TINY_RET_E_CONSTRUCT;
            break;
        }
        thiz->_BleOperation = BleOperation_Create(thiz->device, runtime);
        if (thiz->_BleOperation == NULL) {
            LOG_E(TAG, "BleOperation_Create failed");
            ret = TINY_RET_E_CONSTRUCT;
            break;
        }

    } while (0);
    return ret;
}

static void BleGateway_Dispose(BleGateway *thiz) {
    RETURN_IF_FAIL(thiz);

    if (thiz->_BleOperation != NULL) {
        BleOperation_Delete(thiz->_BleOperation);
        thiz->_BleOperation = NULL;
    }

    if (thiz->device != NULL) {
        UpnpDevice_Delete(thiz->device);
        thiz->device = NULL;
    }
}

void BleGateway_Delete(BleGateway *thiz) {
    RETURN_IF_FAIL(thiz);

    BleGateway_Dispose(thiz);
    tiny_free(thiz);
}

const char * BleGateway_GetDeviceType(BleGateway *thiz) {
   RETURN_VAL_IF_FAIL(thiz, NULL);

    return BLEGATEWAY_DEVICE_TYPE;
}

BleOperation * BleGateway_GetBleOperation(BleGateway *thiz) {
    RETURN_VAL_IF_FAIL(thiz, NULL);

    return thiz->_BleOperation;
}

TinyRet BleGateway_Start(BleGateway *thiz) {
    RETURN_VAL_IF_FAIL(thiz, TINY_RET_E_ARG_NULL);

    return UpnpRuntime_Register(thiz->runtime, thiz->device, action_handler, thiz);
}

TinyRet BleGateway_Stop(BleGateway *thiz) {
    RETURN_VAL_IF_FAIL(thiz, TINY_RET_E_ARG_NULL);

    return UpnpRuntime_Unregister(thiz->runtime, UpnpDevice_GetDeviceId(thiz->device));
}

static UpnpCode action_handler(UpnpAction *action, void *ctx) {
    BleGateway *thiz = (BleGateway *)ctx;

    LOG_D(TAG, "action_handler");

    if (BleOperation_IsImplemented(thiz->_BleOperation, (UpnpService *)UpnpAction_GetParentService(action))) {
        return BleOperation_OnAction(thiz->_BleOperation, action);
    }

    return UPNP_ERR_INVALID_ACTION;
}

