/* Automatic generated by DeviceToC */

#ifndef __BLEGATEWAY_H__
#define __BLEGATEWAY_H__

#include "tiny_base.h"
#include "UpnpDeviceConfig.h"
#include "UpnpRuntime.h"
#include "BleOperation.h"

TINY_BEGIN_DECLS

#define BLEGATEWAY_DEVICE_TYPE          "urn:schemas-upnp-org:device:BleGateway:0.1"

struct _BleGateway;
typedef struct _BleGateway BleGateway;

BleGateway * BleGateway_New(UpnpDeviceConfig *config, UpnpRuntime *runtime);
void BleGateway_Delete(BleGateway *thiz);

const char * BleGateway_GetDeviceType(BleGateway *thiz);
BleOperation * BleGateway_GetBleOperation(BleGateway *thiz);

TinyRet BleGateway_Start(BleGateway *thiz);
TinyRet BleGateway_Stop(BleGateway *thiz);

TINY_END_DECLS

#endif /* __BLEGATEWAY_H__ */
