/* Automatic generated by DeviceToClazz */

package upnps.api.host.device.mediaserver;

import android.content.Context;
import android.util.Log;

import java.util.HashMap;
import java.util.Map;

import upnp.typedef.device.urn.DeviceType;
import upnp.typedef.device.urn.ServiceType;
import upnp.typedef.error.UpnpError;
import upnp.typedef.device.Device;
import upnp.typedef.device.invocation.ActionInfo;
import upnp.typedef.exception.UpnpException;

import upnps.manager.UpnpManager;
import upnps.manager.handler.MyActionHandler;
import upnps.manager.handler.MyCompletionHandler;
import upnps.manager.host.config.DeviceConfig;
import upnps.manager.host.ServiceStub;

public class MediaServer implements MyActionHandler {

    private static final String TAG = "MediaServer";

    /**
     * deviceType & serviceType
     */
    public static final DeviceType DEVICE_TYPE = new DeviceType("MediaServer", "1");
    public static final ServiceType SERVICE_ContentDirectory =  new ServiceType("ContentDirectory", "1");
    public static final ServiceType SERVICE_ConnectionManager =  new ServiceType("ConnectionManager", "1");

    /**
     * serviceId
     */
    private static final String ID_ContentDirectory = "urn:upnp-org:serviceId:ContentDirectory";
    private static final String ID_ConnectionManager = "urn:upnp-org:serviceId:ConnectionManager";

    /**
     * device & service handler;
     */

    private Device _device;
    private Map<String, ServiceStub> _services = new HashMap<String, ServiceStub>();

    public MediaServer(Context context, DeviceConfig config) throws UpnpException {
        _device = config.build(context);
        _services.put(ID_ContentDirectory, new ContentDirectory(_device.getService(ID_ContentDirectory)));
        _services.put(ID_ConnectionManager, new ConnectionManager(_device.getService(ID_ConnectionManager)));
    }

    public String getDeviceId() {
        return _device.getDeviceId();
    }

    public void start(MyCompletionHandler handler) throws UpnpException {
        UpnpManager.getHost().register(_device, handler, this);
    }

    public void stop(MyCompletionHandler handler) throws UpnpException {
        UpnpManager.getHost().unregister(_device, handler);
    }

    @Override
    public UpnpError onAction(ActionInfo info) {
        ServiceStub handler = _services.get(info.getServiceId());
        if (handler == null) {
            Log.e(TAG, "service not found: " + info.getServiceId());
            return UpnpError.UPNP_INTERNAL_ERROR;
        }

        return handler.onAction(info);
    }

    public ContentDirectory getContentDirectory() {
        return (ContentDirectory)_services.get(ID_ContentDirectory);
    }

    public ConnectionManager getConnectionManager() {
        return (ConnectionManager)_services.get(ID_ConnectionManager);
    }

}
