/* Automatic generated by DeviceToClazz */

package upnps.api.host.device.mediarenderer;

import android.content.Context;
import android.util.Log;

import java.util.HashMap;
import java.util.Map;

import upnp.typedef.device.urn.DeviceType;
import upnp.typedef.error.UpnpError;
import upnp.typedef.device.Device;
import upnp.typedef.device.invocation.ActionInfo;
import upnp.typedef.exception.UpnpException;

import upnps.manager.UpnpManager;
import upnps.manager.handler.MyActionHandler;
import upnps.manager.handler.MyCompletionHandler;
import upnps.manager.host.config.DeviceConfig;
import upnps.manager.host.ServiceHandler;

public class MediaRenderer implements MyActionHandler {

    private static final String TAG = "MediaRenderer";

    /**
     * deviceType
     */
    public static final DeviceType DEVICE_TYPE = new DeviceType("MediaRenderer", "1");

    /**
     * serviceId
     */
    public static final String ID_AVTransport = "urn:upnp-org:serviceId:AVTransport";
    public static final String ID_ConnectionManager = "urn:upnp-org:serviceId:ConnectionManager";
    public static final String ID_RenderingControl = "urn:upnp-org:serviceId:RenderingControl";

    /**
     * device & service handler;
     */

    private Device _device;
    private Map<String, ServiceHandler> _services = new HashMap<String, ServiceHandler>();

    public MediaRenderer(Context context, DeviceConfig config) throws UpnpException {
        _device = config.build(context);
        _services.put(ID_AVTransport, new AVTransport(_device));
        _services.put(ID_ConnectionManager, new ConnectionManager(_device));
        _services.put(ID_RenderingControl, new RenderingControl(_device));
    }

    public String getDeviceId() {
        return _device.getDeviceId();
    }

    public void start(MyCompletionHandler handler) throws UpnpException {
        UpnpManager.getHost().register(_device, handler, this);
    }

    public void stop(MyCompletionHandler handler) throws UpnpException {
        UpnpManager.getHost().unregister(_device, handler);
    }

    @Override
    public UpnpError onAction(ActionInfo info) {
        ServiceHandler handler = _services.get(info.getServiceId());
        if (handler == null) {
            Log.e(TAG, "service not found: " + info.getServiceId());
            return UpnpError.UPNP_INTERNAL_ERROR;
        }

        return handler.onAction(info);
    }

    public AVTransport getAVTransport() {
        return (AVTransport)_services.get(ID_AVTransport);
    }

    public ConnectionManager getConnectionManager() {
        return (ConnectionManager)_services.get(ID_ConnectionManager);
    }

    public RenderingControl getRenderingControl() {
        return (RenderingControl)_services.get(ID_RenderingControl);
    }

}
