/* Automatic generated by DeviceToClazz */

package upnps.api.host.device.binarylight;

import android.util.Log;

import upnp.typedef.datatype.DataType;
import upnp.typedef.device.Action;
import upnp.typedef.device.Device;
import upnp.typedef.device.urn.ServiceType;
import upnp.typedef.error.UpnpError;
import upnp.typedef.device.Argument;
import upnp.typedef.device.Service;
import upnp.typedef.device.invocation.ActionInfo;
import upnp.typedef.device.invocation.EventInfo;
import upnp.typedef.device.invocation.EventInfoCreator;
import upnp.typedef.exception.UpnpException;

import upnp.typedef.property.AllowedValueList;
import upnp.typedef.property.AllowedValueRange;
import upnp.typedef.property.PropertyDefinition;
import upnps.manager.UpnpManager;
import upnps.manager.host.ServiceHandler;

public class SwitchPower extends ServiceHandler {
    private static final String TAG = "SwitchPower";
    private static final ServiceType SERVICE_TYPE =  new ServiceType("SwitchPower", "1");

    //-------------------------------------------------------
    // Action Names (3)
    //-------------------------------------------------------
    public static final String ACTION_GetTarget = "GetTarget";
    public static final String _GetTarget_ARG_RetTargetValue = "RetTargetValue";
    public static final String ACTION_SetTarget = "SetTarget";
    public static final String _SetTarget_ARG_newTargetValue = "newTargetValue";
    public static final String ACTION_GetStatus = "GetStatus";
    public static final String _GetStatus_ARG_ResultStatus = "ResultStatus";

    //-------------------------------------------------------
    // Property Name (2)
    //-------------------------------------------------------
    public static final String PROPERTY_Status = "Status";
    public static final String PROPERTY_Target = "Target";

    //-------------------------------------------------------
    // Property value defined (0)
    //-------------------------------------------------------

    //-------------------------------------------------------
    // Action Result (3)
    //-------------------------------------------------------

    public class GetTarget_Result {
        public Boolean theRetTargetValue;
    }

    // SetTarget has no Result

    public class GetStatus_Result {
        public Boolean theResultStatus;
    }


    //-------------------------------------------------------
    // Action Handler (3)
    //-------------------------------------------------------

    public interface Handler {
        UpnpError onGetTarget(GetTarget_Result result);
        UpnpError onSetTarget(Boolean thenewTargetValue);
        UpnpError onGetStatus(GetStatus_Result result);
    }

    private UpnpError handle_GetTarget(ActionInfo info) {
        GetTarget_Result result = new GetTarget_Result();

        UpnpError error = _handler.onGetTarget(result);
        if (! error.equals(UpnpError.OK)) {
            return error;
        }

        if (! info.setArgumentValue(_GetTarget_ARG_RetTargetValue, result.theRetTargetValue, Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        return UpnpError.OK;
    }

    private UpnpError handle_SetTarget(ActionInfo info) {
        Boolean thenewTargetValue = (Boolean)info.getArgumentValue(_SetTarget_ARG_newTargetValue);

        UpnpError error = _handler.onSetTarget(thenewTargetValue);
        if (! error.equals(UpnpError.OK)) {
            return error;
        }

        return UpnpError.OK;
    }

    private UpnpError handle_GetStatus(ActionInfo info) {
        GetStatus_Result result = new GetStatus_Result();

        UpnpError error = _handler.onGetStatus(result);
        if (! error.equals(UpnpError.OK)) {
            return error;
        }

        if (! info.setArgumentValue(_GetStatus_ARG_ResultStatus, result.theResultStatus, Argument.Direction.OUT)) {
            Log.d(TAG, "setArgumentValue: false");
            return UpnpError.UPNP_ARGUMENT_VALUE_INVALID;
        }

        return UpnpError.OK;
    }

    //-------------------------------------------------------
    // Method
    //-------------------------------------------------------

    private Service _service;
    private Handler _handler;

    public SwitchPower(Device device) {
        _service = new Service(SERVICE_TYPE);
        _service.setServiceId(toServiceId(SERVICE_TYPE));
        _service.setScpdUrl(toScpdUrl(device.getDeviceId(), SERVICE_TYPE));
        _service.setControlUrl(toCtrlUrl(device.getDeviceId(), SERVICE_TYPE));
        _service.setEventSubUrl(toEventUrl(device.getDeviceId(), SERVICE_TYPE));

        Action _GetTarget = new Action(ACTION_GetTarget);
        _GetTarget.addArgument(new Argument(_GetTarget_ARG_RetTargetValue, Argument.Direction.OUT, PROPERTY_Target));
        _service.addAction(_GetTarget);

        Action _SetTarget = new Action(ACTION_SetTarget);
        _SetTarget.addArgument(new Argument(_SetTarget_ARG_newTargetValue, Argument.Direction.IN, PROPERTY_Target));
        _service.addAction(_SetTarget);

        Action _GetStatus = new Action(ACTION_GetStatus);
        _GetStatus.addArgument(new Argument(_GetStatus_ARG_ResultStatus, Argument.Direction.OUT, PROPERTY_Status));
        _service.addAction(_GetStatus);

        PropertyDefinition _Status = new PropertyDefinition(PROPERTY_Status, DataType.BOOLEAN, true);
        _service.addProperty(_Status);

        PropertyDefinition _Target = new PropertyDefinition(PROPERTY_Target, DataType.BOOLEAN, false);
        _service.addProperty(_Target);

        device.addService(_service);
    }

    public void setHandler(Handler handler) {
        _handler = handler;
    }

    @Override
    public UpnpError onAction(ActionInfo info) {
        if (_handler == null) {
           Log.e(TAG, "handler is null");
           return UpnpError.UPNP_ACTION_NOT_IMPLEMENTED;
        }

        if (info.getAction().getName().equals(ACTION_GetTarget)) {
            return handle_GetTarget(info);
        }

        if (info.getAction().getName().equals(ACTION_SetTarget)) {
            return handle_SetTarget(info);
        }

        if (info.getAction().getName().equals(ACTION_GetStatus)) {
            return handle_GetStatus(info);
        }

        return UpnpError.UPNP_ACTION_NOT_IMPLEMENTED;
    }

    public void sendEvents() {
        EventInfo info = EventInfoCreator.create(_service);

        try {
            UpnpManager.getHost().sendEvents(info);
        } catch (UpnpException e) {
            e.printStackTrace();
        }
    }

    public void setStatus(Boolean theStatus) {
         _service.setPropertyValue(PROPERTY_Status, theStatus);
    }

}
